import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      paddingBottom: 110,
    },
    
    header: {
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
      paddingHorizontal: 22,
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 16 : 20,
      paddingBottom: 64,
      borderBottomLeftRadius: 32,
      borderBottomRightRadius: 32,
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
    },
    backButton: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
      marginLeft: -4,
      minWidth: 44,
      minHeight: 44,
    },
    backText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '700',
      marginLeft: 4,
    },
    headerTitle: {
      fontSize: 26,
      fontWeight: '800',
      color: '#FFFFFF',
      letterSpacing: -0.3,
    },
    headerUrdu: {
      fontSize: 15,
      color: 'rgba(255, 255, 255, 0.85)',
      marginTop: 4,
      fontWeight: '500',
    },

    mainCard: {
      backgroundColor: colors.card,
      marginHorizontal: 18,
      borderRadius: 22,
      padding: 20,
      marginTop: -44,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.35 : 0.07,
      shadowRadius: 12,
      elevation: 4,
      marginBottom: 16,
    },
    fieldLabel: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.textPrimary,
      marginBottom: 10,
    },
    
    dropdownBtn: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 14,
      paddingVertical: 14,
      paddingHorizontal: 16,
      marginBottom: 16,
      minHeight: 52,
    },
    dropdownText: {
      fontSize: 15,
      color: colors.inputText,
      fontWeight: '600',
    },
    dropdownPlaceholder: {
      color: colors.inputPlaceholder,
    },
    
    dropdownList: {
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      marginTop: -10,
      marginBottom: 16,
      overflow: 'hidden',
    },
    dropdownItem: {
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      minHeight: 48,
      justifyContent: 'center',
    },
    dropdownItemText: {
      fontSize: 14,
      color: colors.textPrimary,
      fontWeight: '600',
    },

    uploadRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    uploadCard: {
      width: '48%',
      backgroundColor: colors.cardElevated,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: colors.border,
      borderRadius: 18,
      paddingVertical: 20,
      alignItems: 'center',
      minHeight: 130,
    },
    uploadIconBg: {
      width: 58,
      height: 58,
      borderRadius: 20,
      backgroundColor: colors.primaryLight,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 10,
    },
    uploadTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    uploadUrdu: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 2,
    },

    previewContainer: {
      alignItems: 'center',
      width: '100%',
    },
    imageWrapper: {
      width: '100%',
      height: 220,
      borderRadius: 18,
      overflow: 'hidden',
      position: 'relative',
      backgroundColor: isDark ? colors.cardElevated : '#F1F5F9',
      borderWidth: 1,
      borderColor: colors.border,
    },
    previewImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    scanLine: {
      position: 'absolute',
      left: 0,
      right: 0,
      height: 4,
      backgroundColor: colors.primary,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.9,
      shadowRadius: 10,
      elevation: 6,
    },
    scanningOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.65)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 20,
    },
    scanningText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '800',
      textAlign: 'center',
    },
    previewActionRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '100%',
      marginTop: 16,
    },
    changeBtn: {
      backgroundColor: isDark ? colors.cardElevated : '#F1F5F9',
      borderRadius: 14,
      paddingVertical: 13,
      paddingHorizontal: 14,
      justifyContent: 'center',
      alignItems: 'center',
      width: '46%',
      borderWidth: 1,
      borderColor: colors.border,
      minHeight: 48,
    },
    changeBtnText: {
      fontSize: 12,
      color: colors.textSecondary,
      fontWeight: '700',
      textAlign: 'center',
    },
    analyzeBtn: {
      backgroundColor: colors.primary,
      borderRadius: 14,
      paddingVertical: 13,
      paddingHorizontal: 14,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      width: '50%',
      minHeight: 48,
    },
    analyzeBtnText: {
      fontSize: 12,
      color: '#FFFFFF',
      fontWeight: '800',
      textAlign: 'center',
    },

    reportCard: {
      backgroundColor: colors.card,
      marginHorizontal: 18,
      borderRadius: 22,
      padding: 20,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.35 : 0.07,
      shadowRadius: 12,
      elevation: 4,
      marginBottom: 16,
    },
    reportHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      paddingBottom: 14,
      marginBottom: 14,
    },
    reportTitle: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    severityBadge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 8,
    },
    severityText: {
      fontSize: 11,
      fontWeight: '800',
    },
    resultDetails: {
      marginBottom: 16,
    },
    resultRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 8,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
    },
    resultLabel: {
      fontSize: 13,
      color: colors.textSecondary,
      fontWeight: '500',
    },
    resultVal: {
      fontSize: 13,
      color: colors.textPrimary,
      fontWeight: '700',
    },
    
    descTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.textPrimary,
      marginTop: 14,
      marginBottom: 4,
    },
    descText: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 22,
    },
    
    aidTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.textPrimary,
      marginTop: 14,
      marginBottom: 8,
    },
    bulletRow: {
      flexDirection: 'row',
      marginBottom: 6,
      paddingRight: 10,
      alignItems: 'flex-start',
    },
    bulletDot: {
      fontSize: 14,
      color: colors.primary,
      marginRight: 8,
      marginTop: 2,
    },
    bulletText: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 22,
      flex: 1,
    },

    reportActions: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingTop: 16,
      marginTop: 6,
    },
    resetBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? colors.cardElevated : '#F1F5F9',
      borderRadius: 14,
      paddingVertical: 14,
      width: '45%',
      borderWidth: 1,
      borderColor: colors.border,
      minHeight: 48,
    },
    resetBtnText: {
      fontSize: 13,
      color: colors.textSecondary,
      fontWeight: '700',
    },
    consultBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
      borderRadius: 14,
      paddingVertical: 14,
      width: '50%',
      minHeight: 48,
    },
    consultBtnText: {
      fontSize: 13,
      color: '#FFFFFF',
      fontWeight: '800',
    },

    tipsCard: {
      backgroundColor: isDark ? 'rgba(37, 99, 235, 0.15)' : '#EFF6FF',
      marginHorizontal: 18,
      borderRadius: 18,
      padding: 16,
      borderWidth: 1,
      borderColor: isDark ? colors.secondaryBorder : '#BFDBFE',
      marginBottom: 16,
    },
    tipsHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    tipsTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.secondary,
    },
    tipsContent: {
      paddingLeft: 4,
    },
    tipText: {
      fontSize: 13,
      color: isDark ? colors.textSecondary : '#1E40AF',
      lineHeight: 20,
      marginBottom: 4,
    },

    modalBg: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.65)',
      justifyContent: 'flex-end',
    },
    modalContainer: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      padding: 24,
      maxHeight: '75%',
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    modalTitle: {
      fontSize: 17,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    modalSub: {
      fontSize: 13,
      color: colors.textSecondary,
      marginBottom: 16,
    },
    
    sampleList: {
      marginBottom: 20,
    },
    sampleItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.cardElevated,
      padding: 12,
      borderRadius: 18,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
      minHeight: 64,
    },
    sampleImg: {
      width: 60,
      height: 60,
      borderRadius: 14,
      marginRight: 16,
    },
    sampleDetails: {
      flex: 1,
    },
    sampleStatus: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    sampleStatusUrdu: {
      fontSize: 12,
      color: colors.textSecondary,
      marginVertical: 2,
    },
    sampleBadge: {
      alignSelf: 'flex-start',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 6,
    },
    sampleBadgeText: {
      fontSize: 10,
      fontWeight: '800',
    },

    bottomNavContainer: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.navBackground,
      borderTopWidth: 1,
      borderTopColor: colors.navBorder,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      elevation: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -3 },
      shadowOpacity: isDark ? 0.35 : 0.08,
      shadowRadius: 10,
    },
    bottomNav: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingTop: 10,
      paddingBottom: Platform.OS === 'ios' ? 28 : 18,
    },
    navItem: {
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 54,
      minHeight: 48,
    },
    navText: {
      fontSize: 11,
      color: colors.navInactive,
      marginTop: 3,
      fontWeight: '600',
    },
    navTextActive: {
      color: colors.navActive,
      fontWeight: '800',
    },
  });
};

const defaultStyles = getStyles(LIGHT_THEME, false);
export default defaultStyles;
