import { StyleSheet, Platform, StatusBar } from 'react-native';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F8FAF9' },
  scrollContent: { paddingBottom: 20 },
  
  header: {
    backgroundColor: '#58D66D',
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 16 : 16,
    paddingBottom: 60,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    marginLeft: -4,
  },
  backText: { color: '#FFF', fontSize: 14, fontWeight: '600', marginLeft: 4 },
  headerTitle: { fontSize: 24, fontWeight: 'bold', color: '#FFF' },
  headerUrdu: { fontSize: 16, color: '#E8F8EA', marginTop: 6, fontWeight: '500' },

  mainCard: {
    backgroundColor: '#FFF',
    marginHorizontal: 20,
    borderRadius: 20,
    padding: 20,
    marginTop: -40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 4,
    marginBottom: 20,
  },
  fieldLabel: { fontSize: 14, fontWeight: 'bold', color: '#333', marginBottom: 10 },
  
  dropdownBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F7F9F8',
    borderWidth: 1,
    borderColor: '#E2E6E4',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  dropdownText: { fontSize: 15, color: '#333', fontWeight: '500' },
  dropdownPlaceholder: { color: '#999' },
  
  dropdownList: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E2E6E4',
    borderRadius: 12,
    marginTop: -10,
    marginBottom: 16,
    overflow: 'hidden',
  },
  dropdownItem: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  dropdownItemText: { fontSize: 14, color: '#333', fontWeight: '500' },

  uploadRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  uploadCard: {
    width: '48%',
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderRadius: 12,
    paddingVertical: 20,
    alignItems: 'center',
  },
  uploadIconBg: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  uploadTitle: { fontSize: 14, fontWeight: 'bold', color: '#333' },
  uploadUrdu: { fontSize: 12, color: '#666', marginTop: 2 },

  previewContainer: {
    alignItems: 'center',
    width: '100%',
  },
  imageWrapper: {
    width: '100%',
    height: 200,
    borderRadius: 16,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#F0F0F0',
  },
  previewImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  scanLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 6,
    backgroundColor: '#58D66D',
    shadowColor: '#58D66D',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 6,
  },
  scanningOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  scanningText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  previewActionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 16,
  },
  changeBtn: {
    backgroundColor: '#F0F0F0',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
    width: '45%',
  },
  changeBtnText: { fontSize: 11, color: '#555', fontWeight: 'bold', textAlign: 'center' },
  analyzeBtn: {
    backgroundColor: '#4CB85C',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '50%',
  },
  analyzeBtnText: { fontSize: 11, color: '#FFF', fontWeight: 'bold', textAlign: 'center' },

  reportCard: {
    backgroundColor: '#FFF',
    marginHorizontal: 20,
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 4,
    marginBottom: 20,
  },
  reportHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
    paddingBottom: 12,
    marginBottom: 12,
  },
  reportTitle: { fontSize: 14, fontWeight: 'bold', color: '#333' },
  severityBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  severityText: { fontSize: 10, fontWeight: 'bold' },
  resultDetails: {
    marginBottom: 16,
  },
  resultRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  resultLabel: { fontSize: 13, color: '#666', fontWeight: '500' },
  resultVal: { fontSize: 13, color: '#333', fontWeight: '700' },
  
  descTitle: { fontSize: 13, fontWeight: 'bold', color: '#333', marginTop: 12, marginBottom: 4 },
  descText: { fontSize: 12, color: '#555', lineHeight: 22 },
  
  aidTitle: { fontSize: 13, fontWeight: 'bold', color: '#333', marginTop: 12, marginBottom: 6 },
  bulletRow: { flexDirection: 'row', marginBottom: 6, paddingRight: 10, alignItems: 'flex-start' },
  bulletDot: { fontSize: 14, color: '#4CB85C', marginRight: 6, marginTop: 2 },
  bulletText: { fontSize: 12, color: '#555', lineHeight: 22, flex: 1 },

  reportActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
    paddingTop: 16,
  },
  resetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F0F0F0',
    borderRadius: 12,
    paddingVertical: 12,
    width: '45%',
  },
  resetBtnText: { fontSize: 13, color: '#555', fontWeight: 'bold' },
  consultBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4CB85C',
    borderRadius: 12,
    paddingVertical: 12,
    width: '50%',
  },
  consultBtnText: { fontSize: 13, color: '#FFF', fontWeight: 'bold' },

  tipsCard: {
    backgroundColor: '#EAF2FD',
    marginHorizontal: 20,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#C6DCF9',
  },
  tipsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  tipsTitle: { fontSize: 14, fontWeight: 'bold', color: '#1A73E8' },
  tipsContent: {
    paddingLeft: 4,
  },
  tipText: { fontSize: 13, color: '#2C5EBD', lineHeight: 18, marginBottom: 2 },

  modalBg: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    maxHeight: '70%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: { fontSize: 16, fontWeight: 'bold', color: '#333' },
  modalSub: { fontSize: 13, color: '#666', marginBottom: 16 },
  
  sampleList: {
    marginBottom: 20,
  },
  sampleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7F9F8',
    padding: 12,
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E2E6E4',
  },
  sampleImg: {
    width: 60,
    height: 60,
    borderRadius: 12,
    marginRight: 16,
  },
  sampleDetails: {
    flex: 1,
  },
  sampleStatus: { fontSize: 14, fontWeight: 'bold', color: '#333' },
  sampleStatusUrdu: { fontSize: 12, color: '#666', marginVertical: 2 },
  sampleBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  sampleBadgeText: { fontSize: 9, fontWeight: 'bold' },

  bottomNavContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#4CB85C',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 10,
    paddingBottom: Platform.OS === 'ios' ? 28 : 22,
  },
  navItem: { alignItems: 'center', justifyContent: 'center', minWidth: 50 },
  navText: { fontSize: 11, color: '#FFF', marginTop: 2, fontWeight: '600' }
});

export default styles;
