import { StyleSheet, Platform, StatusBar } from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8FAF9',
  },
  header: {
    backgroundColor: '#58D66D',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 14 : 14,
    paddingBottom: 20,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  backButton: {
    padding: 2,
  },
  headerTitleBlock: {
    alignItems: 'center',
  },
  headerTitle: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Outfit' : 'sans-serif-medium',
  },
  headerSubtitle: {
    color: '#E8F8EA',
    fontSize: 12,
    marginTop: 2,
  },
  scrollContainer: {
    padding: 16,
    paddingBottom: 40,
    gap: 16,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    gap: 12,
  },
  emptyText: {
    fontSize: 16,
    color: '#64748B',
    fontWeight: '600',
  },
  shopNowBtn: {
    backgroundColor: '#4CB85C',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 20,
    marginTop: 8,
  },
  shopNowBtnText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  itemsWrapper: {
    gap: 12,
  },
  itemCard: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E8F2EC',
    flexDirection: 'row',
    alignItems: 'center',
  },
  itemImgBox: {
    width: 60,
    height: 60,
    borderRadius: 12,
    backgroundColor: '#F3FBF5',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    overflow: 'hidden',
  },
  itemImg: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  itemDetails: {
    flex: 1,
    gap: 2,
  },
  itemNameText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1E293B',
  },
  itemNameUrdu: {
    fontSize: 12,
    color: '#10B981',
    fontWeight: '600',
  },
  itemStrengthText: {
    fontSize: 11,
    color: '#64748B',
  },
  itemPriceText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#4CB85C',
    marginTop: 2,
  },
  itemControls: {
    alignItems: 'flex-end',
    gap: 10,
  },
  counterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    overflow: 'hidden',
    height: 28,
  },
  counterBtn: {
    width: 26,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
  },
  counterVal: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#1E293B',
    paddingHorizontal: 10,
  },
  deleteBtn: {
    padding: 2,
  },
  cardContainer: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E8F2EC',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 4,
    elevation: 1,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    paddingBottom: 10,
    marginBottom: 12,
  },
  cardHeaderTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#1E293B',
    textTransform: 'uppercase',
  },
  addressBody: {
    gap: 4,
  },
  buyerNameText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1E293B',
  },
  addressText: {
    fontSize: 12,
    color: '#64748B',
    lineHeight: 18,
  },
  phoneText: {
    fontSize: 12,
    color: '#475569',
    fontWeight: '500',
  },
  changeAddressLink: {
    marginTop: 8,
  },
  changeAddressLinkText: {
    fontSize: 12,
    color: '#4CB85C',
    fontWeight: 'bold',
  },
  summaryTable: {
    gap: 8,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  summaryRowTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 2,
  },
  summaryLabel: {
    fontSize: 12,
    color: '#64748B',
  },
  summaryValue: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1E293B',
  },
  totalLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1E293B',
  },
  totalValue: {
    fontSize: 15,
    fontWeight: '800',
    color: '#4CB85C',
  },
  divider: {
    height: 1,
    backgroundColor: '#F1F5F9',
    marginVertical: 4,
  },
  paymentOptions: {
    gap: 10,
  },
  paymentCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 12,
  },
  paymentCardSelected: {
    borderColor: '#4CB85C',
    backgroundColor: '#F3FBF5',
  },
  radioDotOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#94A3B8',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  radioDotInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#4CB85C',
  },
  paymentInfo: {
    flex: 1,
    gap: 2,
  },
  paymentName: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#1E293B',
  },
  paymentDesc: {
    fontSize: 11,
    color: '#64748B',
  },
  placeOrderBtn: {
    backgroundColor: '#58D66D',
    borderRadius: 16,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
    shadowColor: '#4CB85C',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  placeOrderBtnDisabled: {
    backgroundColor: '#94A3B8',
    shadowOpacity: 0,
    elevation: 0,
  },
  placeOrderBtnText: {
    color: '#FFF',
    fontSize: 15,
    fontWeight: 'bold',
  }
});

export default styles;
