import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME, PALETTE } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
      paddingHorizontal: 18,
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 14 : 14,
      paddingBottom: 22,
      borderBottomLeftRadius: 28,
      borderBottomRightRadius: 28,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.35 : 0.08,
      shadowRadius: 10,
      elevation: 5,
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
    },
    backButton: {
      minWidth: 44,
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerTitleBlock: {
      alignItems: 'center',
    },
    headerTitle: {
      color: '#FFFFFF',
      fontSize: 20,
      fontWeight: '800',
      letterSpacing: -0.2,
      fontFamily: Platform.OS === 'ios' ? 'Outfit' : 'sans-serif-medium',
    },
    headerSubtitle: {
      color: 'rgba(255, 255, 255, 0.85)',
      fontSize: 12,
      marginTop: 2,
      fontWeight: '500',
    },
    scrollContainer: {
      padding: 16,
      paddingBottom: 48,
      gap: 16,
    },
    emptyContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 70,
      gap: 14,
    },
    emptyText: {
      fontSize: 16,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    shopNowBtn: {
      backgroundColor: colors.primary,
      paddingHorizontal: 26,
      paddingVertical: 14,
      borderRadius: 24,
      marginTop: 8,
      minHeight: 48,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 2,
    },
    shopNowBtnText: {
      color: '#FFFFFF',
      fontWeight: '800',
      fontSize: 14,
    },
    itemsWrapper: {
      gap: 12,
    },
    itemCard: {
      backgroundColor: colors.card,
      borderRadius: 18,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: 'row',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.25 : 0.04,
      shadowRadius: 6,
      elevation: 2,
    },
    itemImgBox: {
      width: 64,
      height: 64,
      borderRadius: 14,
      backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : colors.cardSecondary,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
      overflow: 'hidden',
    },
    itemImg: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    itemDetails: {
      flex: 1,
      gap: 3,
    },
    itemNameText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    itemNameUrdu: {
      fontSize: 12,
      color: colors.primary,
      fontWeight: '600',
    },
    itemStrengthText: {
      fontSize: 11,
      color: colors.textSecondary,
    },
    itemPriceText: {
      fontSize: 14,
      fontWeight: '800',
      color: isDark ? '#34D399' : PALETTE.emerald700,
      marginTop: 2,
    },
    itemControls: {
      alignItems: 'flex-end',
      gap: 10,
    },
    counterRow: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      overflow: 'hidden',
      height: 36,
      backgroundColor: isDark ? colors.surfaceAlt : '#F8FAFC',
    },
    counterBtn: {
      width: 36,
      height: 36,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : '#F1F5F9',
    },
    counterVal: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textPrimary,
      paddingHorizontal: 10,
      minWidth: 28,
      textAlign: 'center',
    },
    deleteBtn: {
      minWidth: 44,
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 4,
    },
    cardContainer: {
      backgroundColor: colors.card,
      borderRadius: 18,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.25 : 0.04,
      shadowRadius: 6,
      elevation: 2,
    },
    cardHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      paddingBottom: 10,
      marginBottom: 12,
    },
    cardHeaderTitle: {
      fontSize: 13,
      fontWeight: '800',
      color: colors.textPrimary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    addressBody: {
      gap: 4,
    },
    buyerNameText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    addressText: {
      fontSize: 12,
      color: colors.textSecondary,
      lineHeight: 18,
    },
    phoneText: {
      fontSize: 12,
      color: colors.textSecondary,
      fontWeight: '500',
    },
    changeAddressLink: {
      marginTop: 8,
      paddingVertical: 4,
    },
    changeAddressLinkText: {
      fontSize: 12,
      color: colors.primary,
      fontWeight: '700',
    },
    summaryTable: {
      gap: 8,
    },
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    summaryRowTotal: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 4,
    },
    summaryLabel: {
      fontSize: 13,
      color: colors.textSecondary,
    },
    summaryValue: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textPrimary,
    },
    totalLabel: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    totalValue: {
      fontSize: 17,
      fontWeight: '900',
      color: isDark ? '#34D399' : PALETTE.emerald700,
    },
    divider: {
      height: 1,
      backgroundColor: colors.border,
      marginVertical: 6,
    },
    paymentOptions: {
      gap: 10,
    },
    paymentCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: colors.border,
      borderRadius: 14,
      padding: 14,
      minHeight: 52,
      backgroundColor: colors.card,
    },
    paymentCardSelected: {
      borderColor: colors.primary,
      backgroundColor: isDark ? 'rgba(16, 185, 129, 0.12)' : 'rgba(16, 185, 129, 0.08)',
    },
    radioDotOuter: {
      width: 20,
      height: 20,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    radioDotInner: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.primary,
    },
    paymentInfo: {
      flex: 1,
      gap: 2,
    },
    paymentName: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    paymentDesc: {
      fontSize: 11,
      color: colors.textSecondary,
    },
    placeOrderBtn: {
      backgroundColor: colors.primary,
      borderRadius: 16,
      minHeight: 52,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 8,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 4,
    },
    placeOrderBtnDisabled: {
      backgroundColor: isDark ? '#334155' : '#94A3B8',
      shadowOpacity: 0,
      elevation: 0,
    },
    placeOrderBtnText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '800',
      letterSpacing: 0.3,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.6)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalCard: {
      width: '100%',
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 20,
      borderWidth: 1,
      borderColor: colors.border,
      elevation: 8,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: colors.textPrimary,
      marginBottom: 14,
    },
    modalInput: {
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 10,
      fontSize: 14,
      color: colors.inputText,
      marginBottom: 10,
    },
    modalBtnRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 10,
      marginTop: 10,
    },
    modalBtnSecondary: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 10,
      backgroundColor: colors.cardSecondary,
    },
    modalBtnSecondaryText: {
      color: colors.textSecondary,
      fontWeight: '600',
    },
    modalBtnPrimary: {
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderRadius: 10,
      backgroundColor: colors.primary,
    },
    modalBtnPrimaryText: {
      color: '#FFFFFF',
      fontWeight: '700',
    },
  });
};

export default getStyles();
