import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  const brandGreen = '#059669'; // Rich emerald
  const darkGreenHeader = '#065F46'; // Deep premium emerald for header
  const lightBg = '#F8FAFC'; // Clean, crisp off-white/slate
  const darkBg = '#0F172A'; // Sleek dark slate
  const cardLight = '#FFFFFF';
  const cardDark = '#1E293B';
  const borderLight = '#E2E8F0';
  const borderDark = '#334155';

  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: isDark ? '#0F172A' : darkGreenHeader,
    },
    header: {
      backgroundColor: isDark ? '#1E293B' : darkGreenHeader,
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 8 : 12,
      paddingBottom: 16,
      paddingHorizontal: 16,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.15,
      shadowRadius: 6,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    backButton: {
      padding: 8,
      marginRight: 6,
      justifyContent: 'center',
      alignItems: 'center',
    },
    avatarContainer: {
      position: 'relative',
      marginRight: 12,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: 'rgba(255, 255, 255, 0.4)',
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
    },
    onlineBadge: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 13,
      height: 13,
      borderRadius: 6.5,
      backgroundColor: '#10B981',
      borderWidth: 2.5,
      borderColor: isDark ? '#1E293B' : darkGreenHeader,
    },
    headerInfo: {
      flex: 1,
    },
    headerTitle: {
      fontSize: 17,
      fontWeight: '800',
      color: '#FFFFFF',
      letterSpacing: -0.2,
    },
    headerSub: {
      fontSize: 11.5,
      color: 'rgba(255, 255, 255, 0.85)',
      marginTop: 2,
      fontWeight: '500',
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    headerActionBtn: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: 'rgba(255, 255, 255, 0.18)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    chatContainer: {
      flex: 1,
      backgroundColor: isDark ? darkBg : lightBg,
    },
    messagesList: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 24,
    },
    disclaimerBanner: {
      backgroundColor: isDark ? 'rgba(245, 158, 11, 0.12)' : '#FFFBEB',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(251, 191, 36, 0.3)' : '#FDE68A',
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
      gap: 10,
      elevation: 1,
      shadowColor: '#D97706',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
    },
    disclaimerText: {
      fontSize: 11.5,
      color: isDark ? '#FDE68A' : '#92400E',
      flex: 1,
      lineHeight: 17,
      fontWeight: '500',
    },
    suggestionsContainer: {
      marginBottom: 16,
    },
    suggestionsTitle: {
      fontSize: 12,
      color: isDark ? '#94A3B8' : '#64748B',
      fontWeight: '700',
      marginBottom: 8,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    suggestionsScroll: {
      gap: 8,
      flexDirection: 'row',
    },
    suggestionChip: {
      backgroundColor: isDark ? cardDark : cardLight,
      borderWidth: 1.2,
      borderColor: isDark ? borderDark : borderLight,
      borderRadius: 22,
      paddingHorizontal: 15,
      paddingVertical: 9,
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 3,
    },
    suggestionChipText: {
      fontSize: 12.5,
      color: isDark ? '#F1F5F9' : '#1E293B',
      fontWeight: '600',
    },
    messageRow: {
      flexDirection: 'row',
      marginVertical: 6,
      alignItems: 'flex-end',
    },
    userMessageRow: {
      justifyContent: 'flex-end',
    },
    assistantMessageRow: {
      justifyContent: 'flex-start',
    },
    assistantMiniAvatar: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: isDark ? cardDark : '#E0F2FE',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 8,
      marginBottom: 4,
      borderWidth: 1,
      borderColor: isDark ? borderDark : '#BAE6FD',
    },
    messageBubble: {
      maxWidth: '85%',
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 12,
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 4,
    },
    userBubble: {
      backgroundColor: brandGreen,
      borderBottomRightRadius: 4,
    },
    assistantBubble: {
      backgroundColor: isDark ? cardDark : cardLight,
      borderBottomLeftRadius: 4,
      borderWidth: 1,
      borderColor: isDark ? borderDark : borderLight,
    },
    messageText: {
      fontSize: 14,
      lineHeight: 22,
    },
    userMessageText: {
      color: '#FFFFFF',
      fontWeight: '500',
    },
    assistantMessageText: {
      color: isDark ? '#F1F5F9' : '#0F172A',
    },
    bubbleFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 8,
      gap: 8,
      paddingTop: 4,
      borderTopWidth: 0.5,
      borderTopColor: isDark ? 'rgba(255, 255, 255, 0.08)' : 'rgba(0, 0, 0, 0.05)',
    },
    messageTime: {
      fontSize: 10,
    },
    userMessageTime: {
      color: 'rgba(255, 255, 255, 0.8)',
    },
    assistantMessageTime: {
      color: isDark ? '#94A3B8' : '#64748B',
    },
    modelBadge: {
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.08)' : '#F1F5F9',
      paddingHorizontal: 7,
      paddingVertical: 2.5,
      borderRadius: 6,
    },
    modelBadgeText: {
      fontSize: 9.5,
      fontWeight: '700',
      color: isDark ? '#94A3B8' : '#475569',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    audioPlayBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? 'rgba(16, 185, 129, 0.15)' : '#ECFDF5',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(16, 185, 129, 0.3)' : '#A7F3D0',
      paddingHorizontal: 10,
      paddingVertical: 4.5,
      borderRadius: 14,
      gap: 5,
    },
    audioPlayText: {
      fontSize: 11,
      fontWeight: '700',
      color: brandGreen,
    },
    typingIndicatorRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 8,
    },
    typingBubble: {
      backgroundColor: isDark ? cardDark : cardLight,
      borderRadius: 18,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: isDark ? borderDark : borderLight,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      elevation: 1,
    },
    typingDot: {
      width: 7,
      height: 7,
      borderRadius: 3.5,
      backgroundColor: brandGreen,
    },
    typingText: {
      fontSize: 12,
      color: isDark ? '#94A3B8' : '#64748B',
      marginLeft: 4,
      fontStyle: 'italic',
    },
    inputBarContainer: {
      backgroundColor: isDark ? cardDark : cardLight,
      borderTopWidth: 1,
      borderColor: isDark ? borderDark : borderLight,
      paddingHorizontal: 14,
      paddingVertical: 10,
      elevation: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: isDark ? 0.3 : 0.06,
      shadowRadius: 6,
    },
    inputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    textInput: {
      flex: 1,
      backgroundColor: isDark ? darkBg : '#F8FAFC',
      borderRadius: 24,
      paddingHorizontal: 16,
      paddingVertical: Platform.OS === 'ios' ? 10 : 8,
      fontSize: 14,
      color: isDark ? '#F8FAFC' : '#0F172A',
      maxHeight: 100,
      borderWidth: 1.2,
      borderColor: isDark ? borderDark : borderLight,
    },
    iconBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      justifyContent: 'center',
      alignItems: 'center',
    },
    micBtn: {
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.08)' : '#F1F5F9',
      borderWidth: 1,
      borderColor: isDark ? borderDark : borderLight,
    },
    micBtnRecording: {
      backgroundColor: '#FEE2E2',
      borderColor: '#FCA5A5',
    },
    sendBtn: {
      backgroundColor: brandGreen,
      elevation: 2,
      shadowColor: brandGreen,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
    },
    sendBtnDisabled: {
      backgroundColor: isDark ? '#334155' : '#CBD5E1',
      elevation: 0,
    },
    recordingOverlay: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: isDark ? 'rgba(239, 68, 68, 0.2)' : '#FEE2E2',
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 14,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(248, 113, 113, 0.3)' : '#FECACA',
    },
    recordingIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    recordingDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: '#EF4444',
    },
    recordingText: {
      fontSize: 13,
      fontWeight: '700',
      color: '#EF4444',
    },
    recordingCancelBtn: {
      padding: 4,
    },
    recordingCancelText: {
      fontSize: 12,
      color: isDark ? '#94A3B8' : '#64748B',
      fontWeight: '600',
    },
    // Markdown & Action Link Styles
    markdownHeader: {
      fontSize: 15,
      fontWeight: '800',
      color: isDark ? '#F1F5F9' : '#0F172A',
      marginTop: 8,
      marginBottom: 4,
      lineHeight: 22,
    },
    bulletRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginVertical: 2,
      paddingLeft: 4,
    },
    bulletDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: brandGreen,
      marginTop: 7,
      marginRight: 8,
    },
    bulletNumber: {
      fontSize: 13,
      fontWeight: '700',
      color: brandGreen,
      marginRight: 4,
      marginTop: 1,
    },
    bulletTextContainer: {
      flex: 1,
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
    },
    bulletText: {
      fontSize: 13.5,
      lineHeight: 20,
      color: isDark ? '#F1F5F9' : '#0F172A',
    },
    paragraphBlock: {
      marginVertical: 3,
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
    },
    actionCardBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: isDark ? 'rgba(16, 185, 129, 0.12)' : '#ECFDF5',
      borderWidth: 1.5,
      borderColor: brandGreen,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
      marginVertical: 6,
      elevation: 2,
      shadowColor: brandGreen,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
    },
    actionCardLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
    },
    actionCardText: {
      fontSize: 13.5,
      fontWeight: '700',
      color: isDark ? '#34D399' : '#065F46',
      flex: 1,
    },
    inlineActionBtn: {
      backgroundColor: brandGreen,
      borderRadius: 10,
      paddingHorizontal: 10,
      paddingVertical: 4,
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 2,
      marginHorizontal: 3,
      elevation: 1,
    },
    inlineActionText: {
      fontSize: 12.5,
      fontWeight: '700',
      color: '#FFFFFF',
    },
  });
};

const defaultStyles = getStyles(LIGHT_THEME, false);
export default defaultStyles;
