import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME, PALETTE } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
    },
    header: {
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 12 : 14,
      paddingBottom: 16,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.35 : 0.08,
      shadowRadius: 10,
      elevation: 5,
    },
    backButton: {
      minWidth: 44,
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerInfo: {
      flex: 1,
      marginLeft: 10,
    },
    headerName: {
      color: '#FFFFFF',
      fontSize: 17,
      fontWeight: '800',
      letterSpacing: -0.2,
    },
    headerRole: {
      color: 'rgba(255, 255, 255, 0.85)',
      fontSize: 12,
      marginTop: 2,
      fontWeight: '500',
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    headerActionBtn: {
      backgroundColor: 'rgba(255,255,255,0.2)',
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: 10,
    },
    loaderContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 60,
    },
    loadingText: {
      marginTop: 12,
      fontSize: 14,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    chatArea: {
      flex: 1,
    },
    messagesList: {
      padding: 16,
      paddingBottom: 24,
    },
    bubbleWrapper: {
      marginBottom: 14,
      maxWidth: '82%',
    },
    alignRight: {
      alignSelf: 'flex-end',
      alignItems: 'flex-end',
    },
    alignLeft: {
      alignSelf: 'flex-start',
      alignItems: 'flex-start',
    },
    bubble: {
      borderRadius: 18,
      paddingHorizontal: 15,
      paddingVertical: 11,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: isDark ? 0.2 : 0.05,
      shadowRadius: 4,
      elevation: 1,
    },
    bubbleMe: {
      backgroundColor: colors.primary,
      borderBottomRightRadius: 4,
    },
    bubblePartner: {
      backgroundColor: colors.card,
      borderBottomLeftRadius: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    messageText: {
      fontSize: 14,
      lineHeight: 20,
    },
    messageTextMe: {
      color: '#FFFFFF',
    },
    messageTextPartner: {
      color: colors.textPrimary,
    },
    bubbleImage: {
      width: 200,
      height: 150,
      borderRadius: 12,
      marginBottom: 6,
    },
    messageTime: {
      fontSize: 10,
      color: colors.textSecondary,
      marginTop: 4,
      marginHorizontal: 4,
    },
    prescriptionWrapper: {
      marginBottom: 16,
      width: '92%',
    },
    prescriptionCard: {
      backgroundColor: colors.card,
      borderRadius: 18,
      borderWidth: 1.5,
      borderColor: colors.primary,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: isDark ? 0.3 : 0.08,
      shadowRadius: 6,
      elevation: 3,
    },
    prescriptionHeader: {
      backgroundColor: colors.primary,
      flexDirection: 'row',
      alignItems: 'center',
      padding: 14,
    },
    prescriptionHeaderTitle: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '800',
    },
    prescriptionHeaderSubtitle: {
      color: 'rgba(255, 255, 255, 0.88)',
      fontSize: 11,
    },
    prescriptionBody: {
      padding: 16,
    },
    prescriptionLabel: {
      fontSize: 12,
      fontWeight: '800',
      color: colors.textSecondary,
      marginBottom: 4,
      textTransform: 'uppercase',
    },
    prescriptionValue: {
      fontSize: 14,
      color: colors.textPrimary,
      fontWeight: '600',
      lineHeight: 20,
    },
    medicineItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 6,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    medicineName: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    medicineDosage: {
      fontSize: 12,
      color: colors.textSecondary,
    },
    resolveButton: {
      backgroundColor: colors.primary,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 14,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      minHeight: 48,
    },
    resolveButtonText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '800',
    },
    resolvedLabel: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surfaceAlt,
      paddingVertical: 12,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    resolvedLabelText: {
      color: colors.primary,
      fontSize: 12,
      fontWeight: '800',
    },
    resolvedBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.card,
      paddingVertical: 14,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    resolvedBannerText: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: '600',
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    iconButton: {
      minWidth: 42,
      minHeight: 42,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 6,
    },
    textInput: {
      flex: 1,
      backgroundColor: colors.inputBackground,
      borderRadius: 22,
      paddingHorizontal: 16,
      paddingVertical: 10,
      fontSize: 14,
      color: colors.inputText,
      maxHeight: 100,
      marginHorizontal: 4,
      borderWidth: 1,
      borderColor: colors.inputBorder,
    },
    sendButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: 4,
    },
    sendButtonDisabled: {
      backgroundColor: isDark ? '#334155' : '#CCC',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.6)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      padding: 20,
      paddingBottom: 40,
      borderTopWidth: 1,
      borderColor: colors.border,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      paddingBottom: 12,
    },
    modalTitle: {
      fontSize: 17,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    modalSubtitle: {
      fontSize: 13,
      color: colors.textSecondary,
      marginBottom: 16,
    },
    imageSelectorGrid: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    imageOptionCard: {
      width: '30%',
      alignItems: 'center',
    },
    imageOptionThumbnail: {
      width: '100%',
      height: 80,
      borderRadius: 12,
      marginBottom: 6,
    },
    imageOptionLabel: {
      fontSize: 11,
      color: colors.textSecondary,
      fontWeight: '700',
      textAlign: 'center',
    },
    prescriptionModalContainer: {
      height: '80%',
      justifyContent: 'flex-end',
    },
    prescriptionModalContent: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      padding: 20,
      flex: 1,
      borderTopWidth: 1,
      borderColor: colors.border,
    },
    formLabel: {
      fontSize: 12,
      fontWeight: '800',
      color: colors.textPrimary,
      marginBottom: 6,
      marginTop: 12,
    },
    formInput: {
      backgroundColor: colors.inputBackground,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      paddingHorizontal: 14,
      paddingVertical: 10,
      fontSize: 13,
      color: colors.inputText,
      marginBottom: 12,
    },
    formHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 12,
      marginBottom: 6,
    },
    addButton: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    addButtonText: {
      fontSize: 12,
      fontWeight: '800',
      color: colors.primary,
      marginLeft: 4,
    },
    medicineFormRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    deleteRowButton: {
      minWidth: 40,
      minHeight: 40,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 6,
    },
    submitPrescriptionButton: {
      backgroundColor: colors.primary,
      borderRadius: 14,
      paddingVertical: 14,
      minHeight: 50,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 20,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
      elevation: 3,
    },
    submitPrescriptionButtonText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '800',
    },
    attachmentPreviewContainer: {
      padding: 10,
      backgroundColor: colors.card,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      flexDirection: 'row',
    },
    attachmentPreviewImage: {
      width: 60,
      height: 60,
      borderRadius: 10,
    },
    attachmentRemoveBtn: { 
      position: 'absolute', 
      top: 5, 
      right: 5, 
      backgroundColor: 'rgba(0,0,0,0.6)', 
      borderRadius: 12, 
      padding: 4 
    },
    vetActionRow: { 
      flexDirection: 'row', 
      paddingHorizontal: 15, 
      paddingVertical: 10, 
      justifyContent: 'space-between', 
      backgroundColor: colors.surfaceAlt,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    vetActionBtnOutline: { 
      flex: 1, 
      borderWidth: 1.5, 
      borderColor: colors.primary, 
      borderRadius: 25, 
      paddingVertical: 10, 
      alignItems: 'center', 
      marginRight: 8, 
      backgroundColor: colors.card,
      minHeight: 46,
      justifyContent: 'center',
    },
    vetActionBtnOutlineText: { 
      color: colors.primary, 
      fontWeight: '800', 
      fontSize: 13 
    },
    vetActionBtnSolid: { 
      flex: 1, 
      backgroundColor: colors.primary, 
      borderRadius: 25, 
      paddingVertical: 10, 
      alignItems: 'center', 
      marginLeft: 8,
      minHeight: 46,
      justifyContent: 'center',
    },
    vetActionBtnSolidText: { 
      color: '#FFFFFF', 
      fontWeight: '800', 
      fontSize: 13 
    },
  });
};

export default getStyles();
