import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 10 : 14,
      paddingBottom: 16,
      paddingHorizontal: 16,
      borderBottomLeftRadius: 26,
      borderBottomRightRadius: 26,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.3 : 0.08,
      shadowRadius: 6,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    backButton: {
      padding: 6,
      marginRight: 8,
      minWidth: 44,
      minHeight: 44,
      justifyContent: 'center',
    },
    avatarContainer: {
      position: 'relative',
      marginRight: 10,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.card,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: isDark ? colors.border : '#E8F8EA',
    },
    onlineBadge: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: '#10B981',
      borderWidth: 2,
      borderColor: colors.card,
    },
    headerInfo: {
      flex: 1,
    },
    headerTitle: {
      fontSize: 17,
      fontWeight: '800',
      color: '#FFFFFF',
      letterSpacing: -0.2,
    },
    headerSub: {
      fontSize: 11,
      color: 'rgba(255, 255, 255, 0.85)',
      marginTop: 1,
      fontWeight: '500',
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    headerActionBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    chatContainer: {
      flex: 1,
    },
    messagesList: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 20,
    },
    disclaimerBanner: {
      backgroundColor: isDark ? 'rgba(245, 158, 11, 0.14)' : '#FEF3C7',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(251, 191, 36, 0.3)' : '#FDE68A',
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
      gap: 10,
    },
    disclaimerText: {
      fontSize: 11.5,
      color: isDark ? '#FDE68A' : '#92400E',
      flex: 1,
      lineHeight: 17,
      fontWeight: '500',
    },
    suggestionsContainer: {
      marginBottom: 16,
    },
    suggestionsTitle: {
      fontSize: 12,
      color: colors.textSecondary,
      fontWeight: '700',
      marginBottom: 8,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    suggestionsScroll: {
      gap: 8,
      flexDirection: 'row',
    },
    suggestionChip: {
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 20,
      paddingHorizontal: 14,
      paddingVertical: 9,
      elevation: 1,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: isDark ? 0.2 : 0.04,
      shadowRadius: 2,
    },
    suggestionChipText: {
      fontSize: 12.5,
      color: colors.textPrimary,
      fontWeight: '600',
    },
    messageRow: {
      flexDirection: 'row',
      marginVertical: 6,
      alignItems: 'flex-end',
    },
    userMessageRow: {
      justifyContent: 'flex-end',
    },
    assistantMessageRow: {
      justifyContent: 'flex-start',
    },
    assistantMiniAvatar: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: isDark ? colors.cardElevated : '#E8F8EA',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 8,
      marginBottom: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    messageBubble: {
      maxWidth: '84%',
      borderRadius: 20,
      paddingHorizontal: 15,
      paddingVertical: 11,
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: isDark ? 0.3 : 0.06,
      shadowRadius: 4,
    },
    userBubble: {
      backgroundColor: colors.primary,
      borderBottomRightRadius: 4,
    },
    assistantBubble: {
      backgroundColor: colors.card,
      borderBottomLeftRadius: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    messageText: {
      fontSize: 14,
      lineHeight: 22,
    },
    userMessageText: {
      color: '#FFFFFF',
      fontWeight: '500',
    },
    assistantMessageText: {
      color: colors.textPrimary,
    },
    bubbleFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 6,
      gap: 8,
    },
    messageTime: {
      fontSize: 10,
    },
    userMessageTime: {
      color: 'rgba(255, 255, 255, 0.8)',
    },
    assistantMessageTime: {
      color: colors.textMuted,
    },
    modelBadge: {
      backgroundColor: isDark ? colors.cardElevated : '#F1F5F9',
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
    },
    modelBadgeText: {
      fontSize: 9,
      fontWeight: '700',
      color: colors.textSecondary,
      textTransform: 'uppercase',
    },
    audioPlayBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? 'rgba(52, 211, 153, 0.15)' : '#E8F8EA',
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 14,
      gap: 5,
    },
    audioPlayText: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.primary,
    },
    typingIndicatorRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 6,
    },
    typingBubble: {
      backgroundColor: colors.card,
      borderRadius: 18,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    typingDot: {
      width: 7,
      height: 7,
      borderRadius: 3.5,
      backgroundColor: colors.primary,
    },
    typingText: {
      fontSize: 12,
      color: colors.textSecondary,
      marginLeft: 4,
      fontStyle: 'italic',
    },
    inputBarContainer: {
      backgroundColor: colors.card,
      borderTopWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 12,
      paddingVertical: 10,
      elevation: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: isDark ? 0.25 : 0.06,
      shadowRadius: 6,
    },
    inputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    textInput: {
      flex: 1,
      backgroundColor: colors.inputBackground,
      borderRadius: 22,
      paddingHorizontal: 16,
      paddingVertical: Platform.OS === 'ios' ? 10 : 8,
      fontSize: 14,
      color: colors.inputText,
      maxHeight: 100,
      borderWidth: 1,
      borderColor: colors.inputBorder,
    },
    iconBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      justifyContent: 'center',
      alignItems: 'center',
    },
    micBtn: {
      backgroundColor: isDark ? colors.cardElevated : '#E8F8EA',
    },
    micBtnRecording: {
      backgroundColor: isDark ? 'rgba(239, 68, 68, 0.25)' : '#FEE2E2',
    },
    sendBtn: {
      backgroundColor: colors.primary,
    },
    sendBtnDisabled: {
      backgroundColor: isDark ? '#334155' : '#CBD5E1',
    },
    recordingOverlay: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: isDark ? 'rgba(239, 68, 68, 0.2)' : '#FEE2E2',
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 14,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(248, 113, 113, 0.3)' : '#FECACA',
    },
    recordingIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    recordingDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: '#EF4444',
    },
    recordingText: {
      fontSize: 13,
      fontWeight: '700',
      color: '#EF4444',
    },
    recordingCancelBtn: {
      padding: 4,
    },
    recordingCancelText: {
      fontSize: 12,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    // Markdown & Action Link Styles
    markdownHeader: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.textPrimary,
      marginTop: 8,
      marginBottom: 4,
      lineHeight: 22,
    },
    bulletRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginVertical: 2,
      paddingLeft: 4,
    },
    bulletDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.primary,
      marginTop: 7,
      marginRight: 8,
    },
    bulletNumber: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.primary,
      marginRight: 4,
      marginTop: 1,
    },
    bulletTextContainer: {
      flex: 1,
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
    },
    bulletText: {
      fontSize: 13.5,
      lineHeight: 20,
      color: colors.textPrimary,
    },
    paragraphBlock: {
      marginVertical: 3,
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
    },
    actionCardBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: isDark ? 'rgba(16, 185, 129, 0.15)' : '#E8F8EA',
      borderWidth: 1.5,
      borderColor: colors.primary,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
      marginVertical: 6,
      elevation: 2,
      shadowColor: '#10B981',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
    },
    actionCardLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
    },
    actionCardText: {
      fontSize: 13.5,
      fontWeight: '700',
      color: isDark ? '#34D399' : '#166534',
      flex: 1,
    },
    inlineActionBtn: {
      backgroundColor: colors.primary,
      borderRadius: 10,
      paddingHorizontal: 10,
      paddingVertical: 4,
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 2,
      marginHorizontal: 3,
    },
    inlineActionText: {
      fontSize: 12.5,
      fontWeight: '700',
      color: '#FFFFFF',
    },
  });
};

const defaultStyles = getStyles(LIGHT_THEME, false);
export default defaultStyles;
