import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME, PALETTE } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
    },
    headerContainer: {
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
      borderBottomLeftRadius: 28,
      borderBottomRightRadius: 28,
      paddingHorizontal: 20,
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 12 : 14,
      paddingBottom: 22,
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.35 : 0.08,
      shadowRadius: 10,
      elevation: 5,
    },
    headerTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 18,
    },
    headerTitle: {
      color: '#FFFFFF',
      fontSize: 24,
      fontWeight: '800',
      letterSpacing: -0.3,
    },
    headerSubtitle: {
      color: 'rgba(255, 255, 255, 0.88)',
      fontSize: 13,
      marginTop: 2,
      fontWeight: '500',
    },
    addButton: {
      width: 46,
      height: 46,
      borderRadius: 23,
      backgroundColor: isDark ? colors.card : '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.3 : 0.12,
      shadowRadius: 6,
      borderWidth: isDark ? 1 : 0,
      borderColor: colors.border,
    },
    tabsContainer: {
      flexDirection: 'row',
      backgroundColor: isDark ? 'rgba(0, 0, 0, 0.3)' : 'rgba(255, 255, 255, 0.22)',
      borderRadius: 16,
      padding: 4,
    },
    tab: {
      flex: 1,
      paddingVertical: 10,
      alignItems: 'center',
      borderRadius: 12,
      minHeight: 44,
      justifyContent: 'center',
    },
    activeTab: {
      backgroundColor: isDark ? colors.card : '#FFFFFF',
    },
    tabText: {
      fontSize: 13,
      fontWeight: '700',
      color: isDark ? colors.textSecondary : 'rgba(255,255,255,0.85)',
    },
    activeTabText: {
      color: colors.primary,
    },
    searchBarContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBackground,
      marginHorizontal: 16,
      marginVertical: 12,
      borderRadius: 14,
      paddingHorizontal: 14,
      height: 50,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.2 : 0.05,
      shadowRadius: 6,
      elevation: 2,
      borderWidth: 1,
      borderColor: colors.border,
    },
    searchInput: {
      flex: 1,
      height: '100%',
      fontSize: 14,
      color: colors.inputText,
    },
    listContainer: {
      paddingHorizontal: 16,
      paddingTop: 4,
      paddingBottom: 90,
    },
    card: {
      backgroundColor: colors.card,
      borderRadius: 18,
      padding: 18,
      marginBottom: 14,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.25 : 0.05,
      shadowRadius: 8,
      elevation: 2,
      borderWidth: 1,
      borderColor: colors.border,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    avatarText: {
      color: '#FFFFFF',
      fontSize: 17,
      fontWeight: '800',
    },
    authorInfo: {
      flex: 1,
    },
    authorName: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    timeAgo: {
      fontSize: 11,
      color: colors.textSecondary,
      marginTop: 2,
    },
    vetBadgeSmall: {
      backgroundColor: isDark ? 'rgba(16, 185, 129, 0.15)' : '#E8F8EA',
      borderRadius: 8,
      paddingHorizontal: 7,
      paddingVertical: 2,
      marginLeft: 6,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(16, 185, 129, 0.3)' : '#A3E6B2',
    },
    vetBadgeSmallText: {
      color: colors.primary,
      fontSize: 10,
      fontWeight: '800',
    },
    postTitle: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.textPrimary,
      marginBottom: 6,
      lineHeight: 22,
    },
    descriptionText: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 22,
      marginBottom: 14,
    },
    cardFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingTop: 12,
    },
    footerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
    },
    actionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 36,
      minWidth: 36,
      gap: 6,
    },
    actionCount: {
      fontSize: 13,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    loaderContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 60,
    },
    loadingText: {
      marginTop: 12,
      fontSize: 14,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    loadingUrduText: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 4,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 32,
      paddingTop: 60,
    },
    emptyText: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
      marginTop: 16,
      textAlign: 'center',
    },
    emptyUrduText: {
      fontSize: 13,
      color: colors.textSecondary,
      marginTop: 4,
      textAlign: 'center',
    },
    retryButton: {
      marginTop: 20,
      backgroundColor: isDark ? 'rgba(16, 185, 129, 0.15)' : '#E8F8EA',
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: colors.primary,
      minHeight: 48,
      justifyContent: 'center',
      alignItems: 'center',
    },
    retryButtonText: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: '800',
    },
    bottomNav: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.bottomNav,
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingVertical: 14,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderTopWidth: isDark ? 1 : 0,
      borderTopColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: isDark ? 0.3 : 0.08,
      shadowRadius: 8,
      elevation: 10,
    },
    navItem: { alignItems: 'center' },
    navText: { fontSize: 10, color: colors.navText, marginTop: 4, fontWeight: '700' },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.6)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      padding: 20,
      paddingTop: 14,
      maxHeight: '90%',
      borderTopWidth: 1,
      borderColor: colors.border,
    },
    modalHandle: {
      width: 44,
      height: 5,
      backgroundColor: isDark ? 'rgba(255,255,255,0.2)' : '#DDD',
      borderRadius: 3,
      alignSelf: 'center',
      marginBottom: 16,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      paddingBottom: 14,
      marginBottom: 16,
    },
    modalTitle: {
      fontSize: 17,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    formLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textPrimary,
      marginBottom: 8,
      marginTop: 10,
    },
    formInput: {
      backgroundColor: colors.inputBackground,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 14,
      color: colors.inputText,
      marginBottom: 6,
    },
    textArea: {
      height: 120,
      textAlignVertical: 'top',
      marginBottom: 4,
    },
    charCount: {
      fontSize: 11,
      color: colors.textSecondary,
      textAlign: 'right',
      marginBottom: 10,
    },
    categoryToggleRow: {
      flexDirection: 'row',
      marginBottom: 6,
      gap: 10,
    },
    categoryPill: {
      flex: 1,
      flexDirection: 'row',
      paddingVertical: 12,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
      minHeight: 46,
    },
    categoryPillActive: {
      backgroundColor: isDark ? 'rgba(16, 185, 129, 0.15)' : '#E8F8EA',
      borderColor: colors.primary,
    },
    categoryPillText: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '700',
    },
    categoryPillTextActive: {
      color: colors.primary,
    },
    warningBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? 'rgba(239, 68, 68, 0.12)' : '#FFF0F0',
      borderRadius: 12,
      padding: 12,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(239, 68, 68, 0.3)' : '#FFCDD2',
    },
    warningText: {
      fontSize: 12,
      color: PALETTE.coral500,
      marginLeft: 8,
      flex: 1,
      fontWeight: '500',
    },
    submitButton: {
      backgroundColor: colors.primary,
      borderRadius: 16,
      paddingVertical: 14,
      minHeight: 52,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 10,
      marginBottom: 24,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
      elevation: 4,
    },
    submitButtonText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '800',
    },
  });
};

export default getStyles();
