import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME, PALETTE } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
    },
    mainContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    headerContainer: {
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
      borderBottomLeftRadius: 30,
      borderBottomRightRadius: 30,
      paddingHorizontal: 20,
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 10 : 14,
      paddingBottom: 22,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: isDark ? 0.35 : 0.12,
      shadowRadius: 12,
      elevation: 6,
    },
    headerTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: 'rgba(255, 255, 255, 0.18)',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.25)',
    },
    headerTitle: {
      color: '#FFFFFF',
      fontSize: 22,
      fontWeight: '800',
      letterSpacing: -0.3,
    },
    headerSubtitle: {
      color: 'rgba(255, 255, 255, 0.88)',
      fontSize: 12,
      marginTop: 2,
      fontWeight: '500',
    },
    headerNewPostBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      paddingHorizontal: 14,
      paddingVertical: 9,
      borderRadius: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      elevation: 3,
      gap: 6,
    },
    headerNewPostText: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: '800',
    },
    searchBarContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? colors.cardElevated : 'rgba(255, 255, 255, 0.22)',
      borderRadius: 16,
      paddingHorizontal: 14,
      height: 48,
      borderWidth: 1,
      borderColor: isDark ? colors.border : 'rgba(255, 255, 255, 0.32)',
    },
    searchIcon: {
      marginRight: 10,
    },
    searchInput: {
      flex: 1,
      height: '100%',
      fontSize: 14,
      color: '#FFFFFF',
    },
    categoryScroll: {
      maxHeight: 52,
      marginVertical: 10,
    },
    categoryScrollContent: {
      paddingHorizontal: 16,
      gap: 8,
      alignItems: 'center',
    },
    categoryPill: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 20,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: isDark ? 0.2 : 0.04,
      shadowRadius: 3,
      elevation: 1,
      gap: 6,
    },
    categoryPillActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
      elevation: 2,
    },
    categoryPillText: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    categoryPillTextActive: {
      color: '#FFFFFF',
    },
    listContainer: {
      paddingHorizontal: 16,
      paddingTop: 4,
      paddingBottom: 110,
    },
    card: {
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 18,
      marginBottom: 14,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: isDark ? 0.3 : 0.06,
      shadowRadius: 8,
      elevation: 2,
      borderWidth: 1,
      borderColor: colors.border,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    authorSection: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
      borderWidth: 2,
      borderColor: colors.primaryBorder || '#A7F3D0',
    },
    avatarText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '800',
    },
    authorDetails: {
      flex: 1,
    },
    authorNameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 6,
    },
    authorName: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    vetBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? 'rgba(16, 185, 129, 0.18)' : '#ECFDF5',
      paddingHorizontal: 7,
      paddingVertical: 2,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(16, 185, 129, 0.35)' : '#A7F3D0',
      gap: 3,
    },
    vetBadgeText: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.primary,
    },
    farmerBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? 'rgba(59, 130, 246, 0.15)' : '#EFF6FF',
      paddingHorizontal: 7,
      paddingVertical: 2,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(59, 130, 246, 0.3)' : '#BFDBFE',
      gap: 3,
    },
    farmerBadgeText: {
      fontSize: 10,
      fontWeight: '700',
      color: '#2563EB',
    },
    timeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 2,
      gap: 4,
    },
    timeText: {
      fontSize: 11,
      color: colors.textMuted,
    },
    postCategoryBadge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
      backgroundColor: isDark ? colors.cardElevated : '#F1F5F9',
      borderWidth: 1,
      borderColor: colors.border,
    },
    postCategoryBadgeText: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    postTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.textPrimary,
      marginBottom: 6,
      lineHeight: 23,
    },
    descriptionText: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 22,
      marginBottom: 14,
    },
    cardDivider: {
      height: 1,
      backgroundColor: colors.border,
      marginBottom: 12,
    },
    cardFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    footerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    actionChip: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? colors.cardElevated : '#F8FAFC',
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 6,
    },
    actionChipLiked: {
      backgroundColor: '#FEF2F2',
      borderColor: '#FECACA',
    },
    actionChipText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    actionChipTextLiked: {
      color: '#EF4444',
    },
    viewMoreRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
    },
    viewMoreText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.primary,
    },
    fabButton: {
      position: 'absolute',
      bottom: 84,
      right: 18,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primary,
      paddingHorizontal: 18,
      paddingVertical: 12,
      borderRadius: 26,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.35,
      shadowRadius: 8,
      elevation: 6,
      gap: 8,
    },
    fabButtonText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '800',
    },
    loaderContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 60,
    },
    loadingText: {
      marginTop: 12,
      fontSize: 14,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 32,
      paddingTop: 50,
      paddingBottom: 40,
    },
    emptyIconCircle: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: isDark ? 'rgba(16, 185, 129, 0.15)' : '#ECFDF5',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 16,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(16, 185, 129, 0.3)' : '#A7F3D0',
    },
    emptyText: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.textPrimary,
      textAlign: 'center',
      marginBottom: 6,
    },
    emptySubtext: {
      fontSize: 13,
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: 20,
      marginBottom: 20,
    },
    emptyCtaButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primary,
      paddingHorizontal: 22,
      paddingVertical: 12,
      borderRadius: 22,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 5,
      elevation: 3,
      gap: 8,
    },
    emptyCtaButtonText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '800',
    },
    bottomNav: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.navBackground,
      borderTopWidth: 1,
      borderTopColor: colors.navBorder,
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingTop: 10,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      elevation: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -3 },
      shadowOpacity: isDark ? 0.35 : 0.08,
      shadowRadius: 10,
    },
    navItem: {
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 54,
      minHeight: 48,
    },
    navText: {
      fontSize: 11,
      color: colors.navInactive,
      marginTop: 3,
      fontWeight: '600',
    },
    navTextActive: {
      color: colors.primary,
      fontWeight: '800',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.65)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 30,
      borderTopRightRadius: 30,
      paddingHorizontal: 22,
      paddingTop: 12,
      paddingBottom: 24,
      maxHeight: '92%',
      borderTopWidth: 1,
      borderColor: colors.border,
    },
    modalHandle: {
      width: 44,
      height: 5,
      backgroundColor: isDark ? 'rgba(255,255,255,0.2)' : '#CBD5E1',
      borderRadius: 3,
      alignSelf: 'center',
      marginBottom: 16,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      paddingBottom: 14,
      marginBottom: 14,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: colors.textPrimary,
      letterSpacing: -0.3,
    },
    modalSubtitle: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 2,
      fontWeight: '500',
    },
    closeModalBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: isDark ? colors.cardElevated : '#F1F5F9',
      justifyContent: 'center',
      alignItems: 'center',
    },
    userPostingBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? colors.cardElevated : '#F8FAFC',
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 14,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: colors.border,
    },
    userPostingAvatar: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 10,
    },
    userPostingAvatarText: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '800',
    },
    userPostingLabel: {
      fontSize: 11,
      color: colors.textSecondary,
    },
    userPostingName: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    formGroup: {
      marginBottom: 14,
    },
    formLabel: {
      fontSize: 13,
      fontWeight: '800',
      color: colors.textPrimary,
      marginBottom: 8,
    },
    formInputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBackground,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      paddingHorizontal: 14,
      height: 48,
    },
    formInput: {
      flex: 1,
      height: '100%',
      fontSize: 14,
      color: colors.inputText,
    },
    formTextareaWrap: {
      backgroundColor: colors.inputBackground,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      padding: 14,
    },
    formTextarea: {
      height: 100,
      fontSize: 14,
      color: colors.inputText,
      textAlignVertical: 'top',
    },
    charCount: {
      fontSize: 11,
      color: colors.textSecondary,
      textAlign: 'right',
      marginTop: 4,
    },
    categoryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    categoryModalPill: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 9,
      borderRadius: 12,
      backgroundColor: isDark ? colors.cardElevated : '#F8FAFC',
      borderWidth: 1,
      borderColor: colors.border,
      gap: 6,
    },
    categoryModalPillActive: {
      backgroundColor: isDark ? 'rgba(16, 185, 129, 0.18)' : '#ECFDF5',
      borderColor: colors.primary,
    },
    categoryModalPillText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    categoryModalPillTextActive: {
      color: colors.primary,
      fontWeight: '800',
    },
    guidelineBox: {
      flexDirection: 'row',
      backgroundColor: isDark ? 'rgba(59, 130, 246, 0.12)' : '#EFF6FF',
      padding: 12,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(59, 130, 246, 0.25)' : '#BFDBFE',
      marginVertical: 6,
      gap: 10,
      alignItems: 'center',
    },
    guidelineText: {
      flex: 1,
      fontSize: 11,
      color: isDark ? '#93C5FD' : '#1E40AF',
      lineHeight: 17,
      fontWeight: '500',
    },
    warningBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? 'rgba(239, 68, 68, 0.12)' : '#FFF0F0',
      borderRadius: 12,
      padding: 12,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(239, 68, 68, 0.3)' : '#FFCDD2',
    },
    warningText: {
      fontSize: 12,
      color: PALETTE.red500,
      marginLeft: 8,
      flex: 1,
      fontWeight: '600',
    },
    submitButton: {
      backgroundColor: colors.primary,
      borderRadius: 16,
      height: 50,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 8,
      marginBottom: 20,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
      elevation: 4,
      gap: 8,
    },
    submitButtonText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '800',
    },
  });
};

export default getStyles();
