import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      paddingBottom: 110,
    },
    
    header: {
      borderBottomLeftRadius: 32,
      borderBottomRightRadius: 32,
      paddingHorizontal: 22,
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 16 : 20,
      paddingBottom: 50,
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
    },
    headerTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 24,
    },
    greeting: {
      fontSize: 22,
      fontWeight: '800',
      color: '#FFFFFF',
      letterSpacing: -0.3,
    },
    userName: {
      fontSize: 14,
      color: 'rgba(255, 255, 255, 0.9)',
      marginTop: 3,
      fontWeight: '500',
    },
    notificationBtn: {
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      width: 44,
      height: 44,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.25)',
    },
    badge: {
      position: 'absolute',
      top: -3,
      right: -3,
      backgroundColor: '#EF4444',
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 3,
      borderWidth: 2,
      borderColor: '#FFFFFF',
    },
    badgeText: {
      color: '#FFFFFF',
      fontSize: 10,
      fontWeight: '800',
    },
    
    statsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 10,
    },
    statItem: {
      flex: 1,
      backgroundColor: isDark ? 'rgba(30, 41, 59, 0.85)' : 'rgba(255, 255, 255, 0.18)',
      paddingVertical: 12,
      paddingHorizontal: 10,
      borderRadius: 16,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(51, 65, 85, 0.6)' : 'rgba(255, 255, 255, 0.25)',
    },
    statValue: {
      fontSize: 22,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    statLabel: {
      fontSize: 11,
      color: 'rgba(255, 255, 255, 0.92)',
      marginTop: 2,
      fontWeight: '700',
      textAlign: 'center',
    },
    statUrdu: {
      fontSize: 10,
      color: 'rgba(255, 255, 255, 0.8)',
      marginTop: 2,
    },

    cardContainer: {
      backgroundColor: colors.card,
      marginHorizontal: 18,
      borderRadius: 22,
      padding: 20,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.3 : 0.06,
      shadowRadius: 10,
      elevation: 3,
      marginBottom: 16,
    },
    overlapCard: {
      marginTop: -32,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    sectionTitle: {
      fontSize: 17,
      fontWeight: '800',
      color: colors.textPrimary,
      letterSpacing: -0.2,
      marginBottom: 14,
    },
    viewAll: {
      fontSize: 13,
      color: colors.primary,
      fontWeight: '700',
      marginBottom: 14,
    },
    
    actionGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    actionItem: {
      alignItems: 'center',
      width: '31%',
      marginBottom: 18,
    },
    iconBox: {
      width: 58,
      height: 58,
      borderRadius: 18,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.2 : 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    actionText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textPrimary,
      textAlign: 'center',
    },
    actionUrdu: {
      fontSize: 10,
      color: colors.textSecondary,
      textAlign: 'center',
      marginTop: 2,
    },
    soonText: {
      fontSize: 9,
      color: '#EF4444',
      fontWeight: '800',
    },

    // AI Banner
    aiBanner: {
      backgroundColor: colors.card,
      borderRadius: 20,
      marginHorizontal: 18,
      marginTop: 4,
      marginBottom: 16,
      padding: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: isDark ? colors.secondaryBorder : 'rgba(37, 99, 235, 0.2)',
      shadowColor: '#2563EB',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.25 : 0.08,
      shadowRadius: 10,
      elevation: 3,
    },
    aiBannerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      gap: 12,
    },
    aiBannerIcon: {
      width: 48,
      height: 48,
      borderRadius: 16,
      backgroundColor: colors.secondary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    aiBannerTitle: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    aiBannerSub: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 2,
      fontWeight: '500',
    },

    // Recent Scans
    scanItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    scanIconBox: {
      width: 44,
      height: 44,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    scanDetails: {
      flex: 1,
    },
    scanTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    scanTime: {
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 3,
    },
    scanStatus: {
      alignItems: 'flex-end',
    },
    scanPercentage: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.textPrimary,
      marginBottom: 3,
    },
    severityText: {
      fontSize: 11,
      fontWeight: '700',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 6,
      overflow: 'hidden',
    },

    loadingContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 30,
    },
    emptyContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 30,
    },
    emptyText: {
      fontSize: 14,
      color: colors.textMuted,
      fontWeight: '600',
    },
    emptyUrduText: {
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 2,
    },

    // Bottom Navigation (HCI 48dp+ targets, active highlight)
    bottomNav: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.navBackground,
      borderTopWidth: 1,
      borderTopColor: colors.navBorder,
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingTop: 10,
      paddingBottom: Platform.OS === 'android' ? 20 : 16,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      elevation: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -3 },
      shadowOpacity: isDark ? 0.35 : 0.08,
      shadowRadius: 10,
    },
    navItem: {
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 54,
      minHeight: 48,
    },
    navText: {
      fontSize: 11,
      color: colors.navInactive,
      marginTop: 3,
      fontWeight: '600',
      textAlign: 'center',
    },
    navTextActive: {
      color: colors.navActive,
      fontWeight: '800',
    },
  });
};

const defaultStyles = getStyles(LIGHT_THEME, false);
export default defaultStyles;
