import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME, PALETTE } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
    },
    header: {
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 12 : 14,
      paddingBottom: 16,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.35 : 0.08,
      shadowRadius: 10,
      elevation: 5,
    },
    backButton: {
      minWidth: 44,
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerTitleContainer: {
      alignItems: 'center',
    },
    headerTitle: {
      color: '#FFFFFF',
      fontSize: 18,
      fontWeight: '800',
      letterSpacing: -0.2,
    },
    headerSubtitle: {
      color: 'rgba(255, 255, 255, 0.85)',
      fontSize: 11,
      marginTop: 2,
      fontWeight: '500',
    },
    loaderContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 60,
    },
    loadingText: {
      marginTop: 12,
      fontSize: 14,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    chatArea: {
      flex: 1,
    },
    listContainer: {
      padding: 16,
      paddingBottom: 30,
    },
    postDetailContainer: {
      marginBottom: 8,
    },
    originalPostCard: {
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 18,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.25 : 0.06,
      shadowRadius: 8,
      elevation: 2,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 18,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 14,
    },
    avatar: {
      width: 46,
      height: 46,
      borderRadius: 23,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    avatarText: {
      color: '#FFFFFF',
      fontSize: 18,
      fontWeight: '800',
    },
    authorInfo: { flex: 1 },
    authorName: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    timeAgo: {
      fontSize: 11,
      color: colors.textSecondary,
      marginTop: 2,
    },
    categoryBadge: {
      backgroundColor: isDark ? 'rgba(16, 185, 129, 0.15)' : '#E8F8EA',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(16, 185, 129, 0.3)' : '#A3E6B2',
    },
    categoryBadgeText: {
      color: colors.primary,
      fontSize: 11,
      fontWeight: '800',
    },
    postTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.textPrimary,
      marginBottom: 10,
      lineHeight: 22,
    },
    postDescription: {
      fontSize: 14,
      color: colors.textSecondary,
      lineHeight: 22,
      marginBottom: 16,
    },
    likesRow: {
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingTop: 12,
    },
    likeButton: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 36,
      gap: 6,
    },
    likesCountText: {
      fontSize: 14,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    repliesTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    repliesTitle: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    repliesCount: {
      color: colors.textSecondary,
      fontWeight: '600',
    },
    noRepliesBox: {
      alignItems: 'center',
      paddingVertical: 28,
      backgroundColor: colors.card,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 14,
    },
    noRepliesText: {
      fontSize: 14,
      color: colors.textSecondary,
      marginTop: 10,
      fontWeight: '600',
    },
    noRepliesUrdu: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 4,
    },
    
    commentCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 14,
      marginBottom: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: isDark ? 0.2 : 0.04,
      shadowRadius: 4,
      elevation: 1,
      borderWidth: 1,
      borderColor: colors.border,
    },
    commentHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    commentAvatar: {
      width: 36,
      height: 36,
      borderRadius: 18,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 10,
    },
    replyAvatar: {
      width: 28,
      height: 28,
      borderRadius: 14,
      marginRight: 8,
    },
    commentAvatarText: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '800',
    },
    commentAuthorInfo: { flex: 1 },
    commentAuthorName: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    vetBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primary,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
      marginLeft: 6,
    },
    vetBadgeText: {
      color: '#FFFFFF',
      fontSize: 9,
      fontWeight: '800',
    },
    commentTime: {
      fontSize: 10,
      color: colors.textSecondary,
      marginTop: 2,
    },
    commentBodyText: {
      fontSize: 13,
      color: colors.textPrimary,
      lineHeight: 22,
      marginBottom: 10,
    },
    commentActionsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    commentActionBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 32,
      gap: 4,
    },
    commentActionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 6,
    },
    commentActionText: {
      fontSize: 12,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    
    nestedRepliesContainer: {
      flexDirection: 'row',
      marginTop: 12,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    nestedLine: {
      width: 2,
      backgroundColor: isDark ? 'rgba(255,255,255,0.1)' : '#E0EBE4',
      borderRadius: 1,
      marginRight: 10,
      marginLeft: 6,
    },
    nestedReplyCard: {
      marginBottom: 10,
      paddingBottom: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    
    replyBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? 'rgba(16, 185, 129, 0.12)' : '#F0FBF2',
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    replyBannerText: {
      flex: 1,
      fontSize: 13,
      color: colors.textPrimary,
      fontWeight: '500',
    },
    
    inputContainer: {
      backgroundColor: colors.card,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingHorizontal: 12,
      paddingTop: 10,
    },
    inputInner: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    inputAvatarSmall: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 8,
    },
    inputAvatarText: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '800',
    },
    textInput: {
      flex: 1,
      backgroundColor: colors.inputBackground,
      borderRadius: 22,
      paddingHorizontal: 16,
      paddingVertical: 10,
      fontSize: 14,
      color: colors.inputText,
      maxHeight: 100,
      marginRight: 8,
      borderWidth: 1,
      borderColor: colors.inputBorder,
    },
    sendButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 3,
    },
    sendButtonDisabled: {
      backgroundColor: isDark ? '#334155' : '#C8C8C8',
      shadowOpacity: 0,
      elevation: 0,
    },
  });
};

export default getStyles();
