import { StyleSheet, Platform, StatusBar } from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8FAF9',
  },
  header: {
    backgroundColor: '#58D66D',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 12 : 12,
    paddingBottom: 14,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  backButton: {
    padding: 4,
  },
  headerTitleContainer: {
    alignItems: 'center',
  },
  headerTitle: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  headerSubtitle: {
    color: '#E8F8EA',
    fontSize: 11,
    marginTop: 2,
  },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#555',
  },
  chatArea: {
    flex: 1,
  },
  listContainer: {
    padding: 16,
  },
  postDetailContainer: {
    marginBottom: 8,
  },
  originalPostCard: {
    backgroundColor: '#FFF',
    borderRadius: 18,
    padding: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#E8F2EC',
    marginBottom: 18,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#58D66D',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarText: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  authorInfo: { flex: 1 },
  authorName: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#222',
  },
  timeAgo: {
    fontSize: 11,
    color: '#999',
    marginTop: 2,
  },
  categoryBadge: {
    backgroundColor: '#E8F8EA',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  categoryBadgeText: {
    color: '#58D66D',
    fontSize: 11,
    fontWeight: 'bold',
  },
  postTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#222',
    marginBottom: 10,
    lineHeight: 22,
  },
  postDescription: {
    fontSize: 14,
    color: '#444',
    lineHeight: 22,
    marginBottom: 16,
  },
  likesRow: {
    borderTopWidth: 1,
    borderTopColor: '#F0F4F0',
    paddingTop: 12,
  },
  likeButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  likesCountText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '600',
  },
  repliesTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  repliesTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#333',
  },
  repliesCount: {
    color: '#888',
    fontWeight: '500',
  },
  noRepliesBox: {
    alignItems: 'center',
    paddingVertical: 28,
    backgroundColor: '#FFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8F2EC',
    marginBottom: 14,
  },
  noRepliesText: {
    fontSize: 14,
    color: '#888',
    marginTop: 10,
    fontWeight: '500',
  },
  noRepliesUrdu: {
    fontSize: 12,
    color: '#AAA',
    marginTop: 4,
  },
  
  commentCard: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
    borderWidth: 1,
    borderColor: '#E8F2EC',
  },
  commentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  commentAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  replyAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    marginRight: 8,
  },
  commentAvatarText: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: 'bold',
  },
  commentAuthorInfo: { flex: 1 },
  commentAuthorName: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#333',
  },
  vetBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#4CB85C',
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 6,
    marginLeft: 6,
  },
  vetBadgeText: {
    color: '#FFF',
    fontSize: 8,
    fontWeight: 'bold',
  },
  commentTime: {
    fontSize: 10,
    color: '#999',
    marginTop: 2,
  },
  commentBodyText: {
    fontSize: 13,
    color: '#444',
    lineHeight: 19,
    marginBottom: 10,
  },
  commentActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#F4F4F4',
  },
  commentActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  commentActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  commentActionText: {
    fontSize: 12,
    color: '#AAA',
    fontWeight: '600',
  },
  
  nestedRepliesContainer: {
    flexDirection: 'row',
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  nestedLine: {
    width: 2,
    backgroundColor: '#E0EBE4',
    borderRadius: 1,
    marginRight: 10,
    marginLeft: 6,
  },
  nestedReplyCard: {
    marginBottom: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F4F4F4',
  },
  
  replyBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FBF2',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: '#D5EFD9',
  },
  replyBannerText: {
    flex: 1,
    fontSize: 13,
    color: '#555',
  },
  
  inputContainer: {
    backgroundColor: '#FFF',
    borderTopWidth: 1,
    borderTopColor: '#E8F2EC',
    paddingHorizontal: 12,
    paddingTop: 10,
  },
  inputInner: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputAvatarSmall: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#58D66D',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  inputAvatarText: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: 'bold',
  },
  textInput: {
    flex: 1,
    backgroundColor: '#F8FAF9',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 9,
    fontSize: 14,
    color: '#333',
    maxHeight: 100,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#E0EBE4',
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#58D66D',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#58D66D',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  sendButtonDisabled: {
    backgroundColor: '#C8C8C8',
    shadowOpacity: 0,
    elevation: 0,
  },
});

export default styles;
