import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
    },
    scrollContent: {
      paddingBottom: 110,
    },
    
    header: {
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
      paddingHorizontal: 20,
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 16 : 20,
      paddingBottom: 54,
      borderBottomLeftRadius: 30,
      borderBottomRightRadius: 30,
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
    },
    headerTitle: {
      fontSize: 26,
      fontWeight: '800',
      color: '#FFFFFF',
      letterSpacing: -0.3,
    },

    searchBarRow: {
      flexDirection: 'row',
      marginTop: 18,
      alignItems: 'center',
      gap: 10,
    },
    searchContainer: {
      flex: 1,
      flexDirection: 'row',
      backgroundColor: colors.card,
      borderRadius: 24,
      alignItems: 'center',
      paddingHorizontal: 16,
      height: 50,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.2 : 0.05,
      shadowRadius: 6,
      elevation: 3,
    },
    searchIcon: {
      marginRight: 8,
    },
    searchInput: {
      flex: 1,
      height: '100%',
      fontSize: 14,
      color: colors.inputText,
      paddingVertical: 0,
    },
    filterBtn: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: colors.card,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.2 : 0.05,
      shadowRadius: 6,
      elevation: 3,
    },
    filterBtnActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },

    statsCardRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      marginTop: -30,
      marginBottom: 16,
      zIndex: 5,
    },
    statCard: {
      backgroundColor: colors.card,
      width: '31%',
      height: 86,
      borderRadius: 18,
      paddingVertical: 8,
      paddingHorizontal: 4,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: isDark ? 0.25 : 0.06,
      shadowRadius: 8,
      elevation: 3,
      borderWidth: 1,
      borderColor: colors.border,
    },
    statValue: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    statLabel: {
      fontSize: 11,
      color: colors.textSecondary,
      marginTop: 2,
      fontWeight: '600',
      textAlign: 'center',
    },

    filterWrapper: {
      marginBottom: 16,
    },
    filterScrollContent: {
      paddingHorizontal: 16,
      gap: 8,
      flexDirection: 'row',
      alignItems: 'center',
    },
    filterChip: {
      height: 38,
      paddingHorizontal: 16,
      borderRadius: 19,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    filterChipActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 2,
    },
    filterChipText: {
      fontSize: 12.5,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    filterChipTextActive: {
      color: '#FFFFFF',
      fontWeight: '800',
    },

    recordsListContainer: {
      paddingHorizontal: 18,
    },
    recordCard: {
      flexDirection: 'row',
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 16,
      alignItems: 'center',
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.25 : 0.04,
      shadowRadius: 6,
      elevation: 2,
      minHeight: 80,
    },
    iconContainer: {
      width: 46,
      height: 46,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 14,
    },
    detailsContainer: {
      flex: 1,
    },
    diseaseTitle: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    animalSub: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 3,
      fontWeight: '500',
    },
    
    badgesRow: {
      flexDirection: 'row',
      marginTop: 8,
      gap: 8,
    },
    badge: {
      paddingVertical: 3,
      paddingHorizontal: 8,
      borderRadius: 8,
    },
    badgeText: {
      fontSize: 10,
      fontWeight: '800',
    },

    rightContainer: {
      alignItems: 'flex-end',
      justifyContent: 'center',
      marginLeft: 8,
    },
    confidenceText: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.textPrimary,
    },

    emptyContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 60,
    },
    emptyText: {
      fontSize: 14,
      color: colors.textMuted,
      fontWeight: '600',
    },
    emptyUrduText: {
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 4,
    },

    bottomNavContainer: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.navBackground,
      borderTopWidth: 1,
      borderTopColor: colors.navBorder,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      elevation: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -3 },
      shadowOpacity: isDark ? 0.35 : 0.08,
      shadowRadius: 10,
    },
    bottomNav: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingTop: 10,
      paddingBottom: Platform.OS === 'android' ? 20 : 18,
    },
    navItem: {
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 54,
      minHeight: 48,
    },
    navText: {
      fontSize: 11,
      color: colors.navInactive,
      marginTop: 3,
      fontWeight: '600',
    },
    navTextActive: {
      color: colors.navActive,
      fontWeight: '800',
    },

    modalBg: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.65)',
      justifyContent: 'flex-end',
    },
    modalContainer: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      padding: 24,
      maxHeight: '85%',
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      paddingBottom: 14,
    },
    modalTitle: {
      fontSize: 17,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    detailImageWrapper: {
      width: '100%',
      height: 200,
      borderRadius: 18,
      overflow: 'hidden',
      marginBottom: 16,
      backgroundColor: isDark ? colors.cardElevated : '#F1F5F9',
      borderWidth: 1,
      borderColor: colors.border,
    },
    detailImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    detailHeaderInfo: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    detailDisease: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    detailDiseaseUrdu: {
      fontSize: 16,
      color: colors.primary,
      marginTop: 4,
      fontWeight: '700',
    },
    detailTable: {
      backgroundColor: colors.cardElevated,
      borderRadius: 18,
      padding: 16,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    tableRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 7,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
    },
    tableLabel: {
      fontSize: 13,
      color: colors.textSecondary,
      fontWeight: '500',
    },
    tableVal: {
      fontSize: 13,
      color: colors.textPrimary,
      fontWeight: '700',
    },
    sectionTitleModal: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.textPrimary,
      marginTop: 14,
      marginBottom: 8,
    },
    detailTextModal: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 22,
    },
    bulletRowModal: {
      flexDirection: 'row',
      marginBottom: 8,
      paddingRight: 10,
      alignItems: 'flex-start',
    },
    bulletDotModal: {
      fontSize: 14,
      color: colors.primary,
      marginRight: 8,
      marginTop: 2,
    },
    bulletTextModal: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 22,
      flex: 1,
    },
    consultVetBtnModal: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
      borderRadius: 14,
      paddingVertical: 14,
      width: '100%',
      marginTop: 10,
      minHeight: 50,
    },
    consultVetBtnTextModal: {
      fontSize: 14,
      color: '#FFFFFF',
      fontWeight: '800',
    },
  });
};

const defaultStyles = getStyles(LIGHT_THEME, false);
export default defaultStyles;
