import { StyleSheet, Platform, StatusBar } from 'react-native';
import fonts from './fonts';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F8FAF9' },
  scrollContent: { paddingBottom: 20 },

  header: {
    backgroundColor: '#F5A623',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 12 : 12,
    paddingBottom: 22,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  refreshLocButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: { fontSize: 24, fontWeight: 'bold', color: '#FFF' },
  headerTitleUrdu: { fontFamily: fonts.urduBold, fontSize: 17, fontWeight: 'bold', color: '#FFF', opacity: 0.95, marginTop: 2, lineHeight: 28 },
  headerSubtitle: { fontSize: 12, color: 'rgba(255,255,255,0.92)', marginTop: 2 },
  headerSubtitleUrdu: { fontFamily: fonts.urduRegular, fontSize: 13, color: 'rgba(255,255,255,0.92)', marginTop: 2, lineHeight: 22 },

  locationBanner: {
    backgroundColor: '#FFF',
    marginHorizontal: 18,
    marginTop: 14,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    borderWidth: 1,
    borderColor: '#EFEFEF',
  },
  locationBannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 10,
  },
  locationIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FFF5E5',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  locationBannerLabel: {
    fontSize: 11,
    color: '#888',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  locationBannerValue: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#222',
    marginTop: 2,
  },
  changeLocBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF5E5',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFE2B8',
    gap: 5,
  },
  changeLocBtnText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#F5A623',
  },

  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#666',
  },

  mainCard: {
    backgroundColor: '#FFF',
    marginHorizontal: 18,
    borderRadius: 20,
    padding: 20,
    marginTop: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  cardHeaderLeft: {
    flex: 1,
    marginRight: 10,
  },
  cardTitle: { fontSize: 16, fontWeight: 'bold', color: '#333' },
  cardTitleSubUrdu: { fontSize: 13, fontWeight: '600', color: '#555', marginTop: 1 },
  cardSubtitle: { fontSize: 11, color: '#888', marginTop: 2 },

  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 80,
  },
  badgeBothWrap: {
    alignItems: 'center',
  },
  statusText: { fontSize: 11, fontWeight: 'bold' },
  statusTextSub: { fontSize: 10, fontWeight: 'bold', marginTop: 1 },

  gaugeContainer: {
    alignItems: 'center',
    marginBottom: 12,
  },
  gaugeCircle: {
    width: 130,
    height: 130,
    borderRadius: 65,
    borderWidth: 9,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  },
  gaugeValue: { fontSize: 38, fontWeight: 'bold' },
  gaugeLabel: { fontSize: 11, color: '#999', marginTop: -2 },

  gaugeDescWrap: {
    alignItems: 'center',
    marginBottom: 22,
    paddingHorizontal: 8,
  },
  gaugeDescEn: {
    textAlign: 'center',
    fontSize: 12,
    color: '#666',
    lineHeight: 18,
  },
  gaugeDescUr: {
    textAlign: 'center',
    fontSize: 12,
    color: '#666',
    lineHeight: 20,
    marginTop: 2,
  },

  metricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  metricBox: {
    alignItems: 'center',
    backgroundColor: '#F7F9F8',
    paddingVertical: 12,
    paddingHorizontal: 6,
    borderRadius: 14,
    width: '31%',
  },
  metricIconBg: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  metricValue: { fontSize: 15, fontWeight: 'bold', color: '#333' },
  metricLabel: { fontSize: 10, color: '#777', marginTop: 2, textAlign: 'center' },
  metricLabelEn: { fontSize: 10, color: '#666', marginTop: 2, textAlign: 'center' },
  metricLabelUr: { fontSize: 9, color: '#888', marginTop: 1, textAlign: 'center' },

  advisoryCard: {
    backgroundColor: '#FFF9F0',
    marginHorizontal: 18,
    marginTop: 14,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#FFE2B8',
  },
  advisoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 6,
  },
  advisoryTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#C67A00',
  },
  advisoryBodyWrap: {},
  advisoryBodyEn: {
    fontSize: 12,
    color: '#664400',
    lineHeight: 18,
  },
  advisoryDivider: {
    height: 1,
    backgroundColor: '#FFE2B8',
    marginVertical: 8,
  },
  advisoryBodyUr: {
    fontSize: 12,
    color: '#664400',
    lineHeight: 20,
    textAlign: 'right',
  },

  forecastHeaderRow: {
    marginBottom: 16,
  },
  forecastTitle: { fontSize: 16, fontWeight: 'bold', color: '#333' },
  forecastSubtitle: { fontSize: 11, color: '#888', marginTop: 2 },
  forecastRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  forecastDay: { width: 44, fontSize: 13, color: '#555', fontWeight: '500' },
  forecastIcon: { width: 28 },
  barContainer: {
    flex: 1,
    height: 6,
    backgroundColor: '#F0F0F0',
    borderRadius: 3,
    marginHorizontal: 10,
    overflow: 'hidden',
  },
  barFill: {
    height: '100%',
    borderRadius: 3,
  },
  forecastRight: { width: 60, alignItems: 'flex-end' },
  forecastTemp: { fontSize: 13, fontWeight: 'bold', color: '#333' },
  forecastThi: { fontSize: 10, fontWeight: '600' },

  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#222',
  },
  modalSubtitle: {
    fontSize: 12,
    color: '#777',
    marginTop: 2,
  },
  modalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F0F0F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  autoDetectBtn: {
    flexDirection: 'row',
    backgroundColor: '#4CB85C',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  autoDetectBtnText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  searchBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F4F6F5',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: '#333',
    paddingVertical: 4,
  },
  searchResultsBox: {
    backgroundColor: '#FDFDFD',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EEE',
    marginBottom: 12,
    maxHeight: 180,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  searchResultName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  searchResultSub: {
    fontSize: 11,
    color: '#888',
  },
  sectionHeader: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#555',
    marginTop: 6,
    marginBottom: 10,
  },
  chipsScroll: {
    maxHeight: 180,
  },
  chipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingBottom: 10,
  },
  districtChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F4F2',
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8E4',
  },
  districtChipActive: {
    backgroundColor: '#F5A623',
    borderColor: '#F5A623',
  },
  districtChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#444',
  },
  districtChipTextActive: {
    color: '#FFF',
  },

  bottomNavContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#4CB85C',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 16,
    paddingBottom: Platform.OS === 'ios' ? 24 : 16,
  },
  navItem: { alignItems: 'center' },
  navText: { fontSize: 10, color: '#A3E6B2', marginTop: 4, fontWeight: '600' },
});

export default styles;
