import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
    },
    header: {
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
      paddingHorizontal: 18,
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 14 : 16,
      paddingBottom: 44,
      borderBottomLeftRadius: 30,
      borderBottomRightRadius: 30,
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
    },
    headerTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 16,
    },
    backButton: {
      padding: 4,
      minWidth: 44,
      minHeight: 44,
      justifyContent: 'center',
    },
    headerTitleBlock: {
      alignItems: 'center',
    },
    headerTitle: {
      color: '#FFFFFF',
      fontSize: 22,
      fontWeight: '800',
      letterSpacing: -0.3,
    },
    headerSubtitle: {
      color: 'rgba(255, 255, 255, 0.88)',
      fontSize: 12,
      marginTop: 2,
      fontWeight: '500',
    },
    cartButton: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: colors.card,
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.2 : 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    cartBadge: {
      position: 'absolute',
      top: -4,
      right: -4,
      backgroundColor: '#EF4444',
      minWidth: 20,
      height: 20,
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: colors.card,
      paddingHorizontal: 3,
    },
    cartBadgeText: {
      color: '#FFFFFF',
      fontSize: 10,
      fontWeight: '800',
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? colors.cardElevated : 'rgba(255, 255, 255, 0.22)',
      borderRadius: 16,
      paddingHorizontal: 14,
      height: 48,
      borderWidth: 1,
      borderColor: isDark ? colors.border : 'rgba(255, 255, 255, 0.3)',
    },
    searchIcon: {
      marginRight: 8,
      color: '#FFFFFF',
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
      color: '#FFFFFF',
      height: '100%',
    },
    categoriesContainer: {
      marginTop: -22,
      marginBottom: 14,
      zIndex: 10,
    },
    categoriesList: {
      paddingHorizontal: 16,
      gap: 8,
    },
    catPill: {
      paddingHorizontal: 16,
      paddingVertical: 9,
      borderRadius: 20,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      minHeight: 38,
      justifyContent: 'center',
      alignItems: 'center',
    },
    catPillActive: {
      paddingHorizontal: 16,
      paddingVertical: 9,
      borderRadius: 20,
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    catPillText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    catPillTextActive: {
      fontSize: 13,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    loaderContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      marginTop: 12,
      fontSize: 14,
      color: colors.textSecondary,
    },
    gridRow: {
      justifyContent: 'space-between',
      paddingHorizontal: 16,
    },
    listContainer: {
      paddingBottom: 100,
      gap: 16,
    },
    card: {
      backgroundColor: colors.card,
      width: '47%',
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: isDark ? 0.25 : 0.05,
      shadowRadius: 6,
      elevation: 2,
      overflow: 'hidden',
    },
    cardImgBox: {
      height: 110,
      backgroundColor: isDark ? colors.cardElevated : '#F1F5F9',
      justifyContent: 'center',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    cardImg: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    cardBody: {
      padding: 12,
      gap: 4,
    },
    medNameEn: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    medNameUr: {
      fontSize: 12,
      color: colors.primary,
      fontWeight: '700',
    },
    medMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    ratingText: {
      fontSize: 11,
      fontWeight: '700',
      color: '#F59E0B',
    },
    metaDivider: {
      fontSize: 11,
      color: colors.textMuted,
    },
    strengthText: {
      fontSize: 11,
      color: colors.textSecondary,
      fontWeight: '500',
      flex: 1,
    },
    priceRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 4,
    },
    priceText: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    stockBadge: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
    },
    stockBadgeText: {
      fontSize: 9,
      fontWeight: '800',
    },
    addBtn: {
      backgroundColor: colors.primary,
      borderRadius: 12,
      height: 38,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 8,
    },
    addBtnDisabled: {
      backgroundColor: isDark ? '#334155' : '#E2E8F0',
    },
    addBtnText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: '800',
    },
    emptyContainer: {
      flex: 0.6,
      justifyContent: 'center',
      alignItems: 'center',
    },
    emptyText: {
      marginTop: 12,
      fontSize: 15,
      fontWeight: '700',
      color: colors.textMuted,
    },
    bottomNav: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.navBackground,
      borderTopWidth: 1,
      borderTopColor: colors.navBorder,
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingVertical: 12,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -3 },
      shadowOpacity: isDark ? 0.35 : 0.08,
      shadowRadius: 10,
      elevation: 5,
    },
    navItem: { 
      alignItems: 'center',
      minWidth: 50,
      minHeight: 48,
      justifyContent: 'center',
    },
    navText: { 
      fontSize: 11, 
      color: colors.navInactive, 
      marginTop: 3, 
      fontWeight: '600',
    },
  });
};

const defaultStyles = getStyles(LIGHT_THEME, false);
export default defaultStyles;
