import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      paddingBottom: 110,
    },
    
    header: {
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
      paddingHorizontal: 24,
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 16 : 20,
      paddingBottom: 64,
      borderBottomLeftRadius: 32,
      borderBottomRightRadius: 32,
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
    },
    headerTitle: {
      fontSize: 26,
      fontWeight: '800',
      color: colors.headerText,
      letterSpacing: -0.3,
    },
    headerUrdu: {
      fontSize: 14,
      color: isDark ? colors.textSecondary : 'rgba(255, 255, 255, 0.85)',
      marginTop: 3,
      fontWeight: '500',
    },

    profileCard: {
      backgroundColor: colors.card,
      marginHorizontal: 20,
      borderRadius: 22,
      padding: 20,
      marginTop: -44,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: isDark ? 0.35 : 0.07,
      shadowRadius: 14,
      elevation: 4,
      marginBottom: 20,
    },
    cardTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      position: 'relative',
    },
    avatar: {
      width: 66,
      height: 66,
      borderRadius: 20,
      backgroundColor: isDark ? colors.primaryLight : '#ECFDF5',
      borderWidth: 2,
      borderColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 16,
    },
    avatarText: {
      fontSize: 24,
      fontWeight: '800',
      color: colors.primary,
    },
    userInfo: {
      flex: 1,
      justifyContent: 'center',
    },
    userName: {
      fontSize: 19,
      fontWeight: '800',
      color: colors.textPrimary,
      letterSpacing: -0.2,
    },
    userNameUrdu: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 2,
    },
    roleBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? colors.primaryLight : '#ECFDF5',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 20,
      marginTop: 6,
      alignSelf: 'flex-start',
      borderWidth: 1,
      borderColor: colors.primaryBorder,
    },
    roleText: {
      fontSize: 11,
      color: colors.primary,
      fontWeight: '700',
    },
    editIconBtn: {
      position: 'absolute',
      top: 0,
      right: 0,
      padding: 8,
      borderRadius: 16,
      backgroundColor: colors.cardElevated,
    },
    statsDivider: {
      height: 1,
      backgroundColor: colors.border,
      marginVertical: 18,
    },
    statsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    statItem: {
      alignItems: 'center',
      flex: 1,
    },
    statValue: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    statLabel: {
      fontSize: 11,
      color: colors.textSecondary,
      marginTop: 4,
      fontWeight: '600',
    },
    statUrdu: {
      fontSize: 10,
      color: colors.textMuted,
      marginTop: 2,
    },

    groupTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textSecondary,
      marginBottom: 8,
      marginLeft: 24,
      marginTop: 10,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    settingsGroup: {
      backgroundColor: colors.card,
      marginHorizontal: 20,
      borderRadius: 18,
      paddingHorizontal: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.2 : 0.04,
      shadowRadius: 8,
      elevation: 2,
    },
    settingsItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 15,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      minHeight: 56, // HCI 48dp+ touch target
    },
    itemIconBg: {
      width: 40,
      height: 40,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 14,
    },
    itemDetails: {
      flex: 1,
    },
    itemTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    itemSubtitle: {
      fontSize: 11,
      color: colors.textMuted,
      marginTop: 2,
    },
    itemVal: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 2,
      fontWeight: '500',
    },

    logoutBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginHorizontal: 20,
      marginTop: 10,
      paddingVertical: 16,
      borderRadius: 16,
      backgroundColor: isDark ? 'rgba(239, 68, 68, 0.12)' : '#FEF2F2',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(248, 113, 113, 0.4)' : '#FCA5A5',
      minHeight: 52,
    },
    logoutBtnText: {
      color: isDark ? '#F87171' : '#DC2626',
      fontSize: 14,
      fontWeight: '700',
    },

    modalBg: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.65)',
      justifyContent: 'flex-end',
    },
    modalContainer: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      padding: 24,
      maxHeight: '85%',
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      paddingBottom: 14,
    },
    modalTitle: {
      fontSize: 17,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    inputLabel: {
      fontSize: 12,
      color: colors.textSecondary,
      fontWeight: '600',
      marginTop: 12,
      marginBottom: 6,
    },
    textInput: {
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 14,
      paddingVertical: 13,
      paddingHorizontal: 16,
      fontSize: 14,
      color: colors.inputText,
      marginBottom: 10,
    },
    saveBtn: {
      backgroundColor: colors.primary,
      borderRadius: 14,
      paddingVertical: 15,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 16,
      minHeight: 50,
    },
    saveBtnText: {
      fontSize: 15,
      color: '#FFFFFF',
      fontWeight: '700',
    },

    bottomNavContainer: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.navBackground,
      borderTopWidth: 1,
      borderTopColor: colors.navBorder,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      elevation: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -3 },
      shadowOpacity: isDark ? 0.3 : 0.08,
      shadowRadius: 10,
    },
    bottomNav: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingTop: 10,
      paddingBottom: Platform.OS === 'ios' ? 28 : 18,
    },
    navItem: {
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 54,
      minHeight: 48,
    },
    navText: {
      fontSize: 11,
      color: colors.navInactive,
      marginTop: 3,
      fontWeight: '600',
    },

    langOption: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 16,
      paddingHorizontal: 18,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 12,
      backgroundColor: colors.cardElevated,
      minHeight: 52,
    },
    langOptionSelected: {
      borderColor: colors.primary,
      backgroundColor: colors.primaryLight,
    },
    langOptionText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.textPrimary,
    },
    langOptionTextSelected: {
      color: colors.primary,
      fontWeight: '800',
    },
  });
};

const defaultStyles = getStyles(LIGHT_THEME, false);
export default defaultStyles;
