import { StyleSheet, Platform } from 'react-native';
import { LIGHT_THEME, PALETTE } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
    },
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      flexGrow: 1,
    },
    topSection: {
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
      paddingHorizontal: 24,
      paddingTop: Platform.OS === 'android' ? 40 : 16,
      paddingBottom: 76,
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
    },
    backButton: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 24,
      minHeight: 44,
    },
    backText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '700',
      marginLeft: 4,
    },
    mainTitle: {
      color: '#FFFFFF',
      fontSize: 32,
      fontWeight: '800',
      marginBottom: 6,
      letterSpacing: -0.5,
    },
    urduTitle: {
      color: 'rgba(255, 255, 255, 0.95)',
      fontSize: 22,
    },
    cardContainer: {
      backgroundColor: colors.card,
      marginHorizontal: 20,
      borderRadius: 28,
      padding: 24,
      marginTop: -44,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: isDark ? 0.35 : 0.08,
      shadowRadius: 14,
      elevation: 6,
      marginBottom: 40,
      borderWidth: 1,
      borderColor: colors.border,
    },
    label: {
      fontSize: 13,
      color: colors.textSecondary,
      marginBottom: 8,
      fontWeight: '700',
      marginTop: 18,
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBackground,
      borderRadius: 16,
      paddingHorizontal: 16,
      minHeight: 56,
      borderWidth: 1,
      borderColor: colors.inputBorder,
    },
    inputIcon: {
      marginRight: 12,
    },
    input: {
      flex: 1,
      height: '100%',
      fontSize: 15,
      color: colors.inputText,
      outlineStyle: 'none',
    },
    roleContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
    },
    roleButton: {
      flex: 1,
      minHeight: 52,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    roleButtonActive: {
      borderColor: colors.primary,
      backgroundColor: isDark ? 'rgba(16, 185, 129, 0.15)' : '#E8F8EA',
    },
    roleText: {
      color: colors.textSecondary,
      fontSize: 14,
      fontWeight: '700',
      textAlign: 'center',
    },
    roleTextActive: {
      color: colors.primary,
    },
    registerBtn: {
      backgroundColor: colors.primary,
      minHeight: 56,
      borderRadius: 18,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
      marginBottom: 20,
      marginTop: 20,
    },
    errorContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? 'rgba(239, 68, 68, 0.15)' : '#FFEBEA',
      padding: 12,
      borderRadius: 12,
      marginTop: 16,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(239, 68, 68, 0.3)' : '#FFCDD2',
    },
    errorText: {
      color: '#EF4444',
      fontSize: 13,
      fontWeight: '600',
      marginLeft: 8,
      flex: 1,
    },
    registerBtnText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '800',
      letterSpacing: 0.2,
    },
    loginContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      flexWrap: 'wrap',
      marginTop: 8,
      marginBottom: 20,
    },
    loginText: {
      color: colors.textSecondary,
      fontSize: 14,
      textAlign: 'center',
    },
    loginLink: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: '800',
      textAlign: 'center',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.6)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalContent: {
      backgroundColor: colors.card,
      width: '90%',
      maxHeight: '65%',
      borderRadius: 24,
      padding: 22,
      elevation: 10,
      shadowColor: '#000',
      shadowOpacity: isDark ? 0.4 : 0.2,
      shadowRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '800',
      marginBottom: 16,
      textAlign: 'center',
      color: colors.textPrimary,
    },
    modalItem: {
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    modalItemText: {
      fontSize: 15,
      color: colors.textPrimary,
      textAlign: 'center',
      fontWeight: '600',
    },
    modalUploadItem: {
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
    },
    modalCloseBtn: {
      marginTop: 16,
      paddingVertical: 14,
      backgroundColor: isDark ? colors.surfaceAlt : '#F1F5F9',
      borderRadius: 14,
      alignItems: 'center',
    },
    modalCloseText: {
      color: colors.textPrimary,
      fontWeight: '700',
    },
  });
};

export default getStyles();
