import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME, PALETTE } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    headerContainer: {
      backgroundColor: isDark ? colors.headerBackground : PALETTE.amber500,
      borderBottomLeftRadius: 28,
      borderBottomRightRadius: 28,
      paddingHorizontal: 20,
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 14 : 14,
      paddingBottom: 24,
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.35 : 0.08,
      shadowRadius: 10,
      elevation: 5,
    },
    headerTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    headerTitle: {
      color: '#FFFFFF',
      fontSize: 26,
      fontWeight: '800',
      letterSpacing: -0.3,
    },
    headerSubtitle: {
      color: 'rgba(255,255,255,0.9)',
      fontSize: 14,
      marginTop: 4,
      fontWeight: '500',
    },
    addButton: {
      minWidth: 46,
      minHeight: 46,
      borderRadius: 23,
      backgroundColor: 'rgba(255, 255, 255, 0.22)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    tabsContainer: {
      flexDirection: 'row',
      backgroundColor: isDark ? 'rgba(0, 0, 0, 0.3)' : 'rgba(255, 255, 255, 0.22)',
      borderRadius: 16,
      padding: 4,
    },
    tab: {
      flex: 1,
      paddingVertical: 10,
      alignItems: 'center',
      borderRadius: 12,
      minHeight: 44,
      justifyContent: 'center',
    },
    activeTab: {
      backgroundColor: isDark ? colors.card : '#FFFFFF',
    },
    tabText: {
      fontSize: 14,
      fontWeight: '700',
      color: isDark ? colors.textSecondary : 'rgba(255,255,255,0.85)',
    },
    activeTabText: {
      color: PALETTE.amber500,
    },
    listContainer: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 90,
    },
    card: {
      backgroundColor: colors.card,
      borderRadius: 18,
      padding: 16,
      marginBottom: 14,
      flexDirection: 'row',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.25 : 0.05,
      shadowRadius: 8,
      elevation: 2,
      borderWidth: 1,
      borderColor: colors.border,
    },
    iconContainer: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: isDark ? 'rgba(16, 185, 129, 0.15)' : '#E8F8EA',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 14,
    },
    detailsContainer: {
      flex: 1,
    },
    vaccineTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    vaccineUrdu: {
      fontSize: 13,
      color: colors.textSecondary,
      marginTop: 2,
      marginBottom: 6,
    },
    metaRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    metaText: {
      fontSize: 12,
      color: colors.textSecondary,
      fontWeight: '500',
    },
    metaDivider: {
      fontSize: 12,
      color: colors.border,
      marginHorizontal: 4,
    },
    statusBadge: {
      backgroundColor: isDark ? 'rgba(16, 185, 129, 0.15)' : '#E8F8EA',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(16, 185, 129, 0.3)' : '#A3E6B2',
    },
    statusText: {
      color: colors.primary,
      fontSize: 12,
      fontWeight: '800',
    },
    bottomNav: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.bottomNav,
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingVertical: 14,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderTopWidth: isDark ? 1 : 0,
      borderTopColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: isDark ? 0.3 : 0.08,
      shadowRadius: 8,
      elevation: 10,
    },
    navItem: { alignItems: 'center' },
    navText: { fontSize: 10, color: colors.navText, marginTop: 4, fontWeight: '700' },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 60,
    },
    emptyText: {
      fontSize: 16,
      color: colors.textSecondary,
      fontWeight: '600',
      marginTop: 16,
    },
  });
};

export default getStyles();
