import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#58D66D' },
  container: { flex: 1, backgroundColor: '#F8FAF9' },
  scrollContent: { flexGrow: 1 },
  topSection: {
    backgroundColor: '#58D66D',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 70,
    alignItems: 'center', 
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginBottom: 20,
    width: '100%',
  },
  backText: { color: '#FFFFFF', fontSize: 16, fontWeight: '600', marginLeft: 4 },
  iconContainer: {
    width: 80,
    height: 80,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  mainTitle: { color: '#FFFFFF', fontSize: 32, fontWeight: 'bold', marginBottom: 8 },
  urduTitle: { color: '#FFFFFF', fontSize: 20 },
  cardContainer: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 24,
    borderRadius: 24,
    padding: 32,
    marginTop: -40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 5,
    marginBottom: 40,
    alignItems: 'center',
  },
  instructionText: { fontSize: 15, color: '#555', marginBottom: 4 },
  phoneNumber: { fontSize: 16, fontWeight: 'bold', color: '#333', marginBottom: 32 },
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 16,
    marginBottom: 32,
    width: '100%',
  },
  otpInput: {
    width: 60,
    height: 60,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#E0E0E0',
    borderRadius: 16,
    fontSize: 28,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  timerText: { fontSize: 13, color: '#777', marginBottom: 8 },
  timerHighlight: { color: '#4CB85C', fontWeight: 'bold' },
  resendLink: { color: '#4CB85C', fontSize: 14, fontWeight: 'bold', marginBottom: 32 },
  verifyBtn: {
    backgroundColor: '#58D66D',
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
    width: '100%',
    shadowColor: '#58D66D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  verifyBtnText: { color: '#FFFFFF', fontSize: 18, fontWeight: 'bold' },
});

export default styles;
