import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME, PALETTE } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: isDark ? colors.headerBackground : colors.primary },
    container: { flex: 1, backgroundColor: colors.background },
    scrollContent: { flexGrow: 1 },
    topSection: {
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
      paddingHorizontal: 24,
      paddingTop: Platform.OS === 'android' ? 24 : 16,
      paddingBottom: 70,
      alignItems: 'center', 
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
    },
    backButton: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      marginBottom: 20,
      width: '100%',
      minHeight: 44,
    },
    backText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700', marginLeft: 4 },
    iconContainer: {
      width: 80,
      height: 80,
      backgroundColor: 'rgba(255, 255, 255, 0.22)',
      borderRadius: 40,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 20,
    },
    mainTitle: { color: '#FFFFFF', fontSize: 32, fontWeight: '800', marginBottom: 6, letterSpacing: -0.5 },
    urduTitle: { color: 'rgba(255, 255, 255, 0.95)', fontSize: 20 },
    cardContainer: {
      backgroundColor: colors.card,
      marginHorizontal: 20,
      borderRadius: 28,
      padding: 30,
      marginTop: -40,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: isDark ? 0.35 : 0.08,
      shadowRadius: 12,
      elevation: 6,
      marginBottom: 40,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    instructionText: { fontSize: 15, color: colors.textSecondary, marginBottom: 4 },
    phoneNumber: { fontSize: 16, fontWeight: '800', color: colors.textPrimary, marginBottom: 28 },
    otpContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 14,
      marginBottom: 28,
      width: '100%',
    },
    otpInput: {
      width: 58,
      height: 62,
      backgroundColor: colors.inputBackground,
      borderWidth: 2,
      borderColor: colors.inputBorder,
      borderRadius: 16,
      fontSize: 28,
      fontWeight: '800',
      color: colors.inputText,
      textAlign: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.2 : 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    timerText: { fontSize: 13, color: colors.textSecondary, marginBottom: 8 },
    timerHighlight: { color: colors.primary, fontWeight: '800' },
    resendLink: { color: colors.primary, fontSize: 14, fontWeight: '800', marginBottom: 28 },
    verifyBtn: {
      backgroundColor: colors.primary,
      paddingVertical: 16,
      borderRadius: 16,
      alignItems: 'center',
      width: '100%',
      minHeight: 54,
      justifyContent: 'center',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    verifyBtnText: { color: '#FFFFFF', fontSize: 17, fontWeight: '800', letterSpacing: 0.3 },
  });
};

export default getStyles();
