import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME, PALETTE } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: { 
      flex: 1, 
      backgroundColor: isDark ? colors.headerBackground : colors.primary, 
    },
    header: { 
      backgroundColor: isDark ? colors.headerBackground : colors.primary, 
      paddingHorizontal: 20, 
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 18 : 22, 
      paddingBottom: 22,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.35 : 0.08,
      shadowRadius: 10,
      elevation: 5,
    },
    headerTopRow: { 
      flexDirection: 'row', 
      alignItems: 'center', 
      justifyContent: 'space-between', 
      marginBottom: 18 
    },
    backBtn: { 
      minWidth: 44,
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
    },
    titleContainer: { alignItems: 'center' },
    headerTitle: { fontSize: 22, fontWeight: '800', color: '#FFF', letterSpacing: -0.3 },
    headerSubtitle: { fontSize: 13, color: 'rgba(255,255,255,0.85)', marginTop: 2, fontWeight: '500' },
    filterBtn: { 
      minWidth: 44,
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
    },
    searchContainer: { 
      flexDirection: 'row', 
      alignItems: 'center', 
      backgroundColor: 'rgba(255,255,255,0.2)', 
      borderRadius: 22, 
      paddingHorizontal: 16, 
      height: 48, 
      borderWidth: 1, 
      borderColor: 'rgba(255,255,255,0.3)' 
    },
    searchIcon: { marginRight: 10, color: '#FFF' },
    searchInput: { flex: 1, fontSize: 14, color: '#FFF' },
    tabsContainer: { 
      flexDirection: 'row', 
      backgroundColor: colors.card, 
      paddingVertical: 12, 
      paddingHorizontal: 12, 
      justifyContent: 'space-between',
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    tabBtn: { 
      paddingVertical: 8, 
      paddingHorizontal: 16, 
      borderRadius: 20,
      minHeight: 40,
      justifyContent: 'center',
      alignItems: 'center',
    },
    tabBtnActive: { backgroundColor: colors.primary },
    tabText: { color: colors.textSecondary, fontWeight: '700', fontSize: 13 },
    tabTextActive: { color: '#FFF' },
    statsContainer: { 
      flexDirection: 'row', 
      backgroundColor: colors.card, 
      paddingBottom: 15, 
      paddingHorizontal: 20, 
      borderBottomWidth: 1, 
      borderBottomColor: colors.border 
    },
    statBox: { flex: 1, alignItems: 'center' },
    statNum: { fontSize: 22, fontWeight: '800', color: colors.textPrimary },
    statLabel: { fontSize: 12, color: colors.textSecondary, marginTop: 4, fontWeight: '600' },
    listContainer: { padding: 16, paddingBottom: 100 },
    card: { 
      backgroundColor: colors.card, 
      borderRadius: 18, 
      padding: 16, 
      marginBottom: 14, 
      elevation: 2, 
      shadowColor: '#000', 
      shadowOffset: { width: 0, height: 2 }, 
      shadowOpacity: isDark ? 0.25 : 0.05, 
      shadowRadius: 6,
      borderWidth: 1,
      borderColor: colors.border,
    },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 },
    userInfoRow: { flexDirection: 'row', alignItems: 'center' },
    avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.primary, justifyContent: 'center', alignItems: 'center', marginRight: 12, position: 'relative' },
    avatarText: { fontSize: 16, fontWeight: '800', color: '#FFF' },
    avatarBadge: { position: 'absolute', top: -2, right: -2, backgroundColor: '#EF4444', width: 14, height: 14, borderRadius: 7, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#FFF' },
    avatarBadgeText: { color: '#FFF', fontSize: 8, fontWeight: 'bold' },
    farmerName: { fontSize: 16, fontWeight: '800', color: colors.textPrimary },
    farmerNameUrdu: { fontSize: 12, color: colors.textSecondary, marginTop: 2 },
    timeText: { fontSize: 12, color: colors.textSecondary },
    animalInfoRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
    animalInfoText: { fontSize: 13, color: colors.textSecondary, fontWeight: '600' },
    reasonText: { fontSize: 14, color: colors.textPrimary, lineHeight: 20, marginBottom: 16 },
    cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 12 },
    statusRow: { flexDirection: 'row', alignItems: 'center' },
    statusText: { fontSize: 12, fontWeight: '700', marginLeft: 6 },
    actionBtn: { 
      flexDirection: 'row', 
      alignItems: 'center',
      minHeight: 36,
      paddingHorizontal: 8,
    },
    actionBtnText: { color: colors.primary, fontWeight: '800', fontSize: 14 },
    resolvedAction: { flexDirection: 'row', alignItems: 'center', minHeight: 36, paddingHorizontal: 8 },
    resolvedActionText: { color: '#64748B', fontWeight: '800', fontSize: 14, marginLeft: 5 },
    emptyContainer: { alignItems: 'center', marginTop: 60 },
    emptyText: { marginTop: 16, fontSize: 16, color: colors.textSecondary, fontWeight: '600' }
  });
};

export default getStyles();
