import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME, PALETTE } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: { 
      flex: 1, 
      backgroundColor: colors.background, 
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0 
    },
    header: { 
      backgroundColor: isDark ? colors.headerBackground : colors.primary, 
      paddingHorizontal: 20, 
      paddingTop: 12, 
      paddingBottom: 22,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.35 : 0.08,
      shadowRadius: 10,
      elevation: 5,
    },
    headerTopRow: { 
      flexDirection: 'row', 
      alignItems: 'center', 
      justifyContent: 'space-between', 
      marginBottom: 18 
    },
    backBtn: { 
      minWidth: 44,
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
    },
    titleContainer: { alignItems: 'center' },
    headerTitle: { fontSize: 22, fontWeight: '800', color: '#FFF', letterSpacing: -0.3 },
    headerSubtitle: { fontSize: 13, color: 'rgba(255,255,255,0.85)', marginTop: 2, fontWeight: '500' },
    filterBtn: { 
      minWidth: 44,
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
    },
    tabsContainer: { marginBottom: 15 },
    tabsScroll: { paddingRight: 20 },
    tabBtn: { 
      paddingVertical: 8, 
      paddingHorizontal: 16, 
      borderRadius: 20, 
      backgroundColor: isDark ? 'rgba(0,0,0,0.3)' : 'rgba(255,255,255,0.22)', 
      marginRight: 10, 
      flexDirection: 'row', 
      alignItems: 'center',
      minHeight: 40,
    },
    tabBtnActive: { backgroundColor: isDark ? colors.card : '#FFF' },
    tabText: { color: isDark ? colors.textSecondary : '#FFF', fontWeight: '700', fontSize: 13 },
    tabTextActive: { color: colors.primary },
    dotUrgent: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#EF4444', marginRight: 6 },
    dotResolved: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.primary, marginRight: 6 },
    searchContainer: { 
      flexDirection: 'row', 
      alignItems: 'center', 
      backgroundColor: colors.inputBackground, 
      borderRadius: 22, 
      paddingHorizontal: 16, 
      height: 48,
      borderWidth: 1,
      borderColor: colors.border,
    },
    searchInput: { flex: 1, fontSize: 14, color: colors.inputText },
    micIcon: { marginLeft: 10 },
    listContainer: { padding: 16, paddingBottom: 100 },
    card: { 
      backgroundColor: colors.card, 
      borderRadius: 18, 
      padding: 16, 
      marginBottom: 14, 
      elevation: 2, 
      shadowColor: '#000', 
      shadowOffset: { width: 0, height: 2 }, 
      shadowOpacity: isDark ? 0.25 : 0.05, 
      shadowRadius: 6,
      borderWidth: 1,
      borderColor: colors.border,
    },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
    userInfoRow: { flexDirection: 'row', alignItems: 'center' },
    avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: isDark ? 'rgba(16, 185, 129, 0.2)' : '#A3E6B2', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
    avatarText: { fontSize: 16, fontWeight: '800', color: isDark ? colors.primaryLight : '#FFF' },
    farmerName: { fontSize: 16, fontWeight: '800', color: colors.textPrimary },
    farmerNameUrdu: { fontSize: 12, color: colors.textSecondary, marginTop: 2 },
    statusBadge: { paddingHorizontal: 12, paddingVertical: 4, borderRadius: 12 },
    statusText: { fontSize: 10, fontWeight: 'bold', color: '#FFF', letterSpacing: 0.5 },
    diseaseText: { fontSize: 16, fontWeight: '700', color: colors.textPrimary, marginTop: 4 },
    diseaseUrduText: { fontSize: 12, color: colors.textSecondary, marginTop: 2, marginBottom: 16 },
    confidenceSection: { marginBottom: 16 },
    confidenceHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
    confidenceLabel: { fontSize: 12, color: colors.textSecondary, fontWeight: '500' },
    confidenceValue: { fontSize: 14, fontWeight: '800', color: colors.textPrimary },
    progressBarBg: { height: 6, backgroundColor: isDark ? 'rgba(255,255,255,0.1)' : '#EEE', borderRadius: 3, overflow: 'hidden' },
    progressBarFill: { height: '100%', borderRadius: 3 },
    cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 12 },
    animalInfoRow: { flexDirection: 'row', alignItems: 'center' },
    timeText: { fontSize: 12, color: colors.textSecondary, marginLeft: 10 },
    reviewBtn: { flexDirection: 'row', alignItems: 'center', minHeight: 36, paddingHorizontal: 6 },
    reviewBtnText: { color: colors.primary, fontWeight: '800', fontSize: 14 },
    emptyContainer: { alignItems: 'center', marginTop: 60 },
    emptyText: { marginTop: 16, fontSize: 16, color: colors.textSecondary, fontWeight: '600' }
  });
};

export default getStyles();
