import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F4F7F5' },
  header: { backgroundColor: '#58D66D', paddingHorizontal: 20, paddingTop: 10, paddingBottom: 20 },
  headerTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 },
  backBtn: { padding: 4 },
  titleContainer: { alignItems: 'center' },
  headerTitle: { fontSize: 22, fontWeight: '700', color: '#FFF' },
  headerSubtitle: { fontSize: 14, color: 'rgba(255,255,255,0.8)', marginTop: 2 },
  filterBtn: { padding: 4 },
  tabsContainer: { marginBottom: 15 },
  tabsScroll: { paddingRight: 20 },
  tabBtn: { paddingVertical: 8, paddingHorizontal: 16, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.2)', marginRight: 10, flexDirection: 'row', alignItems: 'center' },
  tabBtnActive: { backgroundColor: '#FFF' },
  tabText: { color: '#FFF', fontWeight: '600', fontSize: 14 },
  tabTextActive: { color: '#58D66D' },
  dotUrgent: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#FF3B30', marginRight: 6 },
  dotResolved: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#58D66D', marginRight: 6 },
  searchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF', borderRadius: 25, paddingHorizontal: 16, height: 48 },
  searchInput: { flex: 1, fontSize: 15, color: '#333' },
  micIcon: { marginLeft: 10 },
  listContainer: { padding: 16, paddingBottom: 100 },
  card: { backgroundColor: '#FFF', borderRadius: 16, padding: 16, marginBottom: 16, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 3 },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  userInfoRow: { flexDirection: 'row', alignItems: 'center' },
  avatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#A3E6B2', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  avatarText: { fontSize: 16, fontWeight: 'bold', color: '#FFF' },
  farmerName: { fontSize: 16, fontWeight: '700', color: '#333' },
  farmerNameUrdu: { fontSize: 12, color: '#888', marginTop: 2 },
  statusBadge: { paddingHorizontal: 12, paddingVertical: 4, borderRadius: 12 },
  statusText: { fontSize: 10, fontWeight: 'bold', color: '#FFF', letterSpacing: 0.5 },
  diseaseText: { fontSize: 16, fontWeight: '600', color: '#333', marginTop: 4 },
  diseaseUrduText: { fontSize: 12, color: '#888', marginTop: 2, marginBottom: 16 },
  confidenceSection: { marginBottom: 16 },
  confidenceHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  confidenceLabel: { fontSize: 12, color: '#666' },
  confidenceValue: { fontSize: 14, fontWeight: 'bold', color: '#333' },
  progressBarBg: { height: 6, backgroundColor: '#EEE', borderRadius: 3, overflow: 'hidden' },
  progressBarFill: { height: '100%', borderRadius: 3 },
  cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: 1, borderTopColor: '#F0F0F0', paddingTop: 12 },
  animalInfoRow: { flexDirection: 'row', alignItems: 'center' },
  timeText: { fontSize: 12, color: '#888', marginLeft: 10 },
  reviewBtn: { flexDirection: 'row', alignItems: 'center' },
  reviewBtnText: { color: '#58D66D', fontWeight: 'bold', fontSize: 14 },
  emptyContainer: { alignItems: 'center', marginTop: 60 },
  emptyText: { marginTop: 16, fontSize: 16, color: '#888' }
});

export default styles;
