import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME, PALETTE } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: { 
      flex: 1, 
      backgroundColor: isDark ? colors.headerBackground : colors.primary 
    },
    headerBg: { 
      backgroundColor: isDark ? colors.headerBackground : colors.primary, 
      paddingBottom: 50 
    },
    headerTop: { 
      backgroundColor: isDark ? colors.headerBackground : colors.primary, 
      paddingHorizontal: 20, 
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 10 : 20, 
      paddingBottom: 20, 
      flexDirection: 'row', 
      alignItems: 'center', 
      justifyContent: 'space-between' 
    },
    titleContainer: { alignItems: 'center' },
    headerTitle: { fontSize: 20, fontWeight: '800', color: '#FFF' },
    headerSubtitle: { fontSize: 13, color: 'rgba(255,255,255,0.85)', marginTop: 2 },
    headerRight: { flexDirection: 'row', alignItems: 'center' },
    notificationBtn: { marginRight: 15, position: 'relative' },
    badge: { position: 'absolute', top: -5, right: -5, backgroundColor: PALETTE.amber500, borderRadius: 10, minWidth: 18, height: 18, justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: colors.primary },
    badgeText: { color: '#FFF', fontSize: 10, fontWeight: 'bold' },
    profileAvatar: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#FFF', justifyContent: 'center', alignItems: 'center' },
    profileAvatarText: { color: colors.primary, fontWeight: '800', fontSize: 12 },
    welcomeCard: { 
      backgroundColor: isDark ? colors.cardSecondary : PALETTE.emerald500, 
      marginHorizontal: 16, 
      marginTop: -15, 
      borderRadius: 20, 
      padding: 20, 
      flexDirection: 'row', 
      justifyContent: 'space-between', 
      alignItems: 'center',
      borderWidth: isDark ? 1 : 0,
      borderColor: colors.border,
      elevation: 4,
    },
    welcomeLeft: { flex: 1 },
    welcomeTitle: { color: '#FFF', fontSize: 18, fontWeight: '800' },
    welcomeUrdu: { color: 'rgba(255,255,255,0.92)', fontSize: 14, marginTop: 4 },
    welcomeSub: { color: 'rgba(255,255,255,0.85)', fontSize: 12, marginTop: 8 },
    availableToggle: { alignItems: 'flex-end' },
    availableText: { color: '#FFF', fontSize: 12, marginBottom: 5, fontWeight: '600' },
    statsContainer: { flexDirection: 'row', paddingHorizontal: 12, marginTop: -30, justifyContent: 'space-between' },
    statCard: { 
      backgroundColor: colors.card, 
      borderRadius: 16, 
      padding: 12, 
      flex: 1, 
      marginHorizontal: 4, 
      elevation: 3, 
      shadowColor: '#000', 
      shadowOffset: { width: 0, height: 2 }, 
      shadowOpacity: isDark ? 0.3 : 0.08, 
      shadowRadius: 4, 
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    statIconRow: { marginBottom: 8 },
    statValue: { fontSize: 20, fontWeight: '800', color: colors.primary },
    statLabel: { fontSize: 10, color: colors.textSecondary, textAlign: 'center', marginTop: 2, fontWeight: '600' },
    sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, marginTop: 25, marginBottom: 15 },
    sectionTitle: { fontSize: 18, fontWeight: '800', color: colors.textPrimary },
    viewAllBtn: { fontSize: 14, color: colors.primary, fontWeight: '700' },
    casesContainer: { paddingHorizontal: 16 },
    caseCard: { 
      backgroundColor: colors.card, 
      borderRadius: 18, 
      padding: 16, 
      marginBottom: 14, 
      elevation: 2, 
      shadowColor: '#000', 
      shadowOffset: { width: 0, height: 2 }, 
      shadowOpacity: isDark ? 0.25 : 0.05, 
      shadowRadius: 6,
      borderWidth: 1,
      borderColor: colors.border,
    },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
    userInfoRow: { flexDirection: 'row', alignItems: 'center' },
    avatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: isDark ? 'rgba(16, 185, 129, 0.2)' : '#A3E6B2', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
    avatarText: { fontSize: 16, fontWeight: 'bold', color: isDark ? colors.primaryLight : '#FFF' },
    farmerName: { fontSize: 16, fontWeight: '700', color: colors.textPrimary },
    farmerNameUrdu: { fontSize: 12, color: colors.textSecondary, marginTop: 2 },
    diseaseText: { fontSize: 16, fontWeight: '700', color: colors.textPrimary, marginTop: 4 },
    diseaseUrduText: { fontSize: 12, color: colors.textSecondary, marginTop: 2, marginBottom: 12 },
    cardFooter: { borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 12 },
    confidenceSection: { marginBottom: 12 },
    confidenceRow: { flexDirection: 'row', alignItems: 'center' },
    statusBadge: { paddingHorizontal: 12, paddingVertical: 4, borderRadius: 12, alignSelf: 'flex-start', marginBottom: 10 },
    statusText: { fontSize: 10, fontWeight: 'bold', color: '#FFF' },
    confidenceValue: { width: 35, fontSize: 12, fontWeight: 'bold', color: PALETTE.coral500 },
    progressBarBg: { flex: 1, height: 6, backgroundColor: isDark ? 'rgba(255,255,255,0.1)' : '#EEE', borderRadius: 3, overflow: 'hidden', marginLeft: 8 },
    progressBarFill: { height: '100%', borderRadius: 3 },
    cardFooterBottom: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    timeText: { fontSize: 12, color: colors.textSecondary },
    reviewBtn: { borderWidth: 1.5, borderColor: colors.primary, borderRadius: 20, paddingVertical: 6, paddingHorizontal: 16 },
    reviewBtnText: { color: colors.primary, fontSize: 12, fontWeight: '700' },
    quickActionsGrid: { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: 12, justifyContent: 'space-between', paddingBottom: 20 },
    actionCard: { 
      backgroundColor: colors.card, 
      width: '48%', 
      borderRadius: 18, 
      padding: 18, 
      marginBottom: 14, 
      alignItems: 'center', 
      elevation: 2, 
      shadowColor: '#000', 
      shadowOffset: { width: 0, height: 2 }, 
      shadowOpacity: isDark ? 0.25 : 0.05, 
      shadowRadius: 6,
      borderWidth: 1,
      borderColor: colors.border,
    },
    actionIconBox: { width: 52, height: 52, borderRadius: 26, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
    actionTitle: { fontSize: 15, fontWeight: '700', color: colors.textPrimary, textAlign: 'center' },
    actionSub: { fontSize: 12, color: colors.textSecondary, marginTop: 4 },
    // AI Banner
    aiBanner: {
      backgroundColor: colors.card,
      borderRadius: 20,
      marginHorizontal: 12,
      marginTop: 4,
      marginBottom: 20,
      padding: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: isDark ? colors.secondaryBorder : 'rgba(37, 99, 235, 0.2)',
      shadowColor: '#2563EB',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.25 : 0.08,
      shadowRadius: 10,
      elevation: 3,
    },
    aiBannerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      gap: 12,
    },
    aiBannerIcon: {
      width: 48,
      height: 48,
      borderRadius: 16,
      backgroundColor: colors.secondary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    aiBannerTitle: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    aiBannerSub: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 2,
    },
    emptyContainer: { alignItems: 'center', paddingVertical: 30 },
    emptyText: { color: colors.textSecondary, fontSize: 14 },
    bottomNav: { 
      flexDirection: 'row', 
      backgroundColor: colors.card, 
      paddingVertical: 14, 
      paddingHorizontal: 20, 
      justifyContent: 'space-between', 
      borderTopWidth: 1, 
      borderTopColor: colors.border, 
      elevation: 10 
    },
    navItem: { alignItems: 'center' },
    navText: { fontSize: 10, color: colors.textSecondary, marginTop: 4, fontWeight: '600' },
    navProfile: { width: 24, height: 24, borderRadius: 12, backgroundColor: isDark ? colors.surfaceAlt : '#E0E0E0', justifyContent: 'center', alignItems: 'center' },
    navProfileText: { fontSize: 10, fontWeight: 'bold', color: colors.textSecondary }
  });
};

export default getStyles();
