import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    headerArea: {
      backgroundColor: isDark ? colors.headerBackground : colors.primary,
      paddingHorizontal: 20,
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 12 : 16,
      paddingBottom: 44,
      borderBottomLeftRadius: 30,
      borderBottomRightRadius: 30,
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
    },
    headerTop: {
      marginBottom: 10,
    },
    backButton: {
      width: 44,
      height: 44,
      justifyContent: 'center',
      marginLeft: -8,
    },
    headerTitleContainer: {
      marginBottom: 18,
    },
    headerTitle: {
      fontSize: 28,
      fontWeight: '800',
      color: '#FFFFFF',
      letterSpacing: -0.3,
    },
    headerSubtitle: {
      fontSize: 16,
      color: 'rgba(255, 255, 255, 0.88)',
      marginTop: 4,
      fontWeight: '500',
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? colors.card : 'rgba(255, 255, 255, 0.22)',
      borderRadius: 18,
      paddingHorizontal: 16,
      height: 52,
      borderWidth: 1,
      borderColor: isDark ? colors.border : 'rgba(255, 255, 255, 0.3)',
    },
    searchIcon: {
      marginRight: 10,
    },
    searchInput: {
      flex: 1,
      fontSize: 15,
      color: isDark ? colors.inputText : '#FFFFFF',
      height: '100%',
    },
    listContainer: {
      paddingHorizontal: 18,
      paddingTop: 10,
      paddingBottom: 40,
      marginTop: -22,
    },
    card: {
      backgroundColor: colors.card,
      borderRadius: 22,
      padding: 18,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.3 : 0.06,
      shadowRadius: 10,
      elevation: 3,
    },
    cardHeader: {
      flexDirection: 'row',
      marginBottom: 16,
    },
    avatarWrapper: {
      marginRight: 16,
      position: 'relative',
    },
    avatarBg: {
      width: 58,
      height: 58,
      borderRadius: 18,
      backgroundColor: isDark ? colors.primaryLight : '#ECFDF5',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: colors.primary,
    },
    avatarText: {
      color: colors.primary,
      fontSize: 24,
      fontWeight: '800',
    },
    statusDot: {
      width: 14,
      height: 14,
      borderRadius: 7,
      borderWidth: 2,
      borderColor: colors.card,
      position: 'absolute',
      bottom: -2,
      right: -2,
    },
    vetInfo: {
      flex: 1,
      justifyContent: 'center',
    },
    nameRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    vetName: {
      fontSize: 18,
      fontWeight: '800',
      color: colors.textPrimary,
      letterSpacing: -0.2,
    },
    vetNameUrdu: {
      fontSize: 13,
      color: colors.textSecondary,
      marginTop: 2,
    },
    vetSpecialization: {
      fontSize: 13,
      color: colors.textSecondary,
      marginTop: 4,
      fontWeight: '500',
    },
    metaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 8,
    },
    loader: {
      marginTop: 50,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.65)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalContent: {
      backgroundColor: colors.card,
      width: '100%',
      borderRadius: 24,
      padding: 24,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.2,
      shadowRadius: 16,
      elevation: 10,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.textPrimary,
      marginBottom: 4,
    },
    modalSubtitle: {
      fontSize: 15,
      color: colors.textSecondary,
      marginBottom: 18,
    },
    inputGroup: {
      marginBottom: 16,
    },
    inputLabel: {
      fontSize: 13,
      color: colors.textPrimary,
      marginBottom: 8,
      fontWeight: '700',
    },
    textInput: {
      backgroundColor: colors.inputBackground,
      borderRadius: 14,
      padding: 13,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      fontSize: 14,
      color: colors.inputText,
    },
    aiRecordNotice: {
      flexDirection: 'row',
      backgroundColor: isDark ? 'rgba(37, 99, 235, 0.15)' : '#EFF6FF',
      padding: 12,
      borderRadius: 12,
      marginBottom: 20,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: isDark ? colors.secondaryBorder : '#BFDBFE',
    },
    aiRecordNoticeText: {
      color: isDark ? colors.secondary : '#1D4ED8',
      fontSize: 13,
      fontWeight: '500',
    },
    modalButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 10,
      gap: 12,
    },
    cancelBtn: {
      flex: 1,
      padding: 14,
      borderRadius: 14,
      backgroundColor: isDark ? colors.cardElevated : '#F1F5F9',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      minHeight: 48,
    },
    cancelBtnText: {
      color: colors.textSecondary,
      fontWeight: '700',
    },
    submitBtn: {
      flex: 1,
      padding: 14,
      borderRadius: 14,
      backgroundColor: colors.primary,
      alignItems: 'center',
      minHeight: 48,
    },
    submitBtnText: {
      color: '#FFFFFF',
      fontWeight: '800',
    },
    ratingContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginRight: 16,
    },
    ratingText: {
      fontSize: 12,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    ratingCount: {
      color: colors.textMuted,
      fontWeight: 'normal',
    },
    locationContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    locationText: {
      fontSize: 12,
      color: colors.textSecondary,
    },
    experienceRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    experienceLabel: {
      fontSize: 13,
      color: colors.textSecondary,
    },
    experienceValue: {
      fontWeight: '800',
      color: colors.textPrimary,
    },
    availabilityBadge: {
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 12,
    },
    availabilityText: {
      fontSize: 11,
      fontWeight: '800',
    },
    actionButtonsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 12,
      gap: 10,
    },
    chatBtn: {
      flex: 1,
      backgroundColor: colors.primary,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 13,
      borderRadius: 22,
      minHeight: 48,
    },
    chatBtnText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '800',
    },
    callBtn: {
      flex: 1,
      backgroundColor: isDark ? colors.cardElevated : '#FFFFFF',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 13,
      borderRadius: 22,
      borderWidth: 1.5,
      borderColor: colors.primary,
      minHeight: 48,
    },
    callBtnText: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: '800',
    },
    bookBtn: {
      backgroundColor: isDark ? 'rgba(245, 158, 11, 0.15)' : '#FFFBEB',
      borderWidth: 1,
      borderColor: colors.accentAmber,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 13,
      borderRadius: 22,
      minHeight: 48,
    },
    bookBtnText: {
      color: colors.accentAmber,
      fontSize: 14,
      fontWeight: '800',
    },
    loaderContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      marginTop: 12,
      fontSize: 14,
      color: colors.textSecondary,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 32,
    },
    emptyText: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.textPrimary,
      marginTop: 16,
      textAlign: 'center',
    },
    retryButton: {
      marginTop: 20,
      backgroundColor: colors.primaryLight,
      paddingHorizontal: 22,
      paddingVertical: 12,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: colors.primaryBorder,
      minHeight: 48,
      justifyContent: 'center',
    },
    retryButtonText: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: '800',
    },
  });
};

const defaultStyles = getStyles(LIGHT_THEME, false);
export default defaultStyles;
