import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME, PALETTE } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: { 
      flex: 1, 
      backgroundColor: isDark ? colors.headerBackground : colors.primary, 
    },
    header: { 
      backgroundColor: isDark ? colors.headerBackground : colors.primary, 
      paddingHorizontal: 20, 
      paddingTop: 12, 
      paddingBottom: 22,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.35 : 0.08,
      shadowRadius: 10,
      elevation: 5,
    },
    headerTopRow: { 
      flexDirection: 'row', 
      alignItems: 'center', 
      justifyContent: 'space-between', 
      marginBottom: 18 
    },
    backBtn: { 
      minWidth: 44,
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
    },
    titleContainer: { alignItems: 'center' },
    headerTitle: { fontSize: 22, fontWeight: '800', color: '#FFF', letterSpacing: -0.3 },
    headerSubtitle: { fontSize: 13, color: 'rgba(255,255,255,0.85)', marginTop: 2, fontWeight: '500' },
    downloadBtn: { 
      minWidth: 44,
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
    },
    searchContainer: { 
      flexDirection: 'row', 
      alignItems: 'center', 
      backgroundColor: 'rgba(255,255,255,0.2)', 
      borderRadius: 22, 
      paddingHorizontal: 16, 
      height: 48,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.3)',
    },
    searchInput: { flex: 1, fontSize: 14, color: '#FFF' },
    micIcon: { marginLeft: 10, color: 'rgba(255,255,255,0.85)' },
    tabsContainer: { 
      backgroundColor: colors.card, 
      paddingVertical: 10, 
      borderBottomWidth: 1, 
      borderBottomColor: colors.border 
    },
    tabsScroll: { paddingHorizontal: 16, gap: 8, flexDirection: 'row', alignItems: 'center' },
    tabBtn: { 
      height: 38,
      paddingHorizontal: 18, 
      borderRadius: 19,
      backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
      minHeight: 38,
    },
    tabBtnActive: { 
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    tabText: { color: colors.textSecondary, fontWeight: '700', fontSize: 13 },
    tabTextActive: { color: '#FFFFFF', fontWeight: '800' },
    listContainer: { padding: 16, paddingBottom: 100 },
    card: { 
      backgroundColor: colors.card, 
      borderRadius: 18, 
      padding: 16, 
      marginBottom: 14, 
      elevation: 2, 
      shadowColor: '#000', 
      shadowOffset: { width: 0, height: 2 }, 
      shadowOpacity: isDark ? 0.25 : 0.05, 
      shadowRadius: 6,
      borderWidth: 1,
      borderColor: colors.border,
    },
    cardTop: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
    iconBox: {
      width: 46,
      height: 46,
      borderRadius: 16,
      backgroundColor: isDark ? 'rgba(16, 185, 129, 0.15)' : '#ECFDF5',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', flex: 1 },
    diseaseName: { fontSize: 16, fontWeight: '800', color: colors.textPrimary, flex: 1 },
    riskBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
    riskBadgeText: { fontSize: 10, fontWeight: 'bold', color: '#FFF' },
    diseaseUrduText: { fontSize: 12, color: colors.textSecondary, marginTop: 2, marginBottom: 12 },
    infoRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10, justifyContent: 'space-between' },
    infoText: { fontSize: 13, color: colors.textSecondary, fontWeight: '500' },
    dotSeparator: { width: 4, height: 4, borderRadius: 2, backgroundColor: colors.border, marginHorizontal: 8 },
    dateText: { fontSize: 12, color: colors.textSecondary },
    modelTag: { flexDirection: 'row', alignItems: 'center', backgroundColor: isDark ? 'rgba(16, 185, 129, 0.15)' : '#E8F8EA', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10 },
    modelTagText: { fontSize: 10, color: colors.primary, fontWeight: '800' },
    confidenceSection: { marginBottom: 16, marginTop: 6 },
    confidenceHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
    confidenceLabel: { fontSize: 12, color: colors.textSecondary, fontWeight: '500' },
    confidenceValue: { fontSize: 14, fontWeight: '800', color: colors.textPrimary },
    progressBarBg: { height: 6, backgroundColor: isDark ? 'rgba(255,255,255,0.1)' : '#EEE', borderRadius: 3, overflow: 'hidden' },
    progressBarFill: { height: '100%', borderRadius: 3 },
    cardFooter: { borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 12, alignItems: 'center' },
    viewFullText: { color: colors.primary, fontSize: 13, fontWeight: '800' },
    emptyContainer: { alignItems: 'center', marginTop: 60 },
    emptyText: { marginTop: 16, fontSize: 16, color: colors.textSecondary, fontWeight: '600' }
  });
};

export default getStyles();
