import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F4F7F5' },
  header: { backgroundColor: '#58D66D', paddingHorizontal: 20, paddingTop: 10, paddingBottom: 20 },
  headerTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 },
  backBtn: { padding: 4 },
  titleContainer: { alignItems: 'center' },
  headerTitle: { fontSize: 20, fontWeight: '700', color: '#FFF' },
  headerSubtitle: { fontSize: 12, color: 'rgba(255,255,255,0.8)', marginTop: 2 },
  settingsBtn: { padding: 4 },
  statsRow: { flexDirection: 'row', justifyContent: 'space-between' },
  statBox: { flex: 1, backgroundColor: '#FFF', borderRadius: 16, paddingVertical: 12, marginHorizontal: 4, alignItems: 'center' },
  statValue: { fontSize: 20, fontWeight: 'bold', color: '#333' },
  statLabel: { fontSize: 12, color: '#888', marginTop: 2 },
  tabsContainer: { backgroundColor: '#FFF', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#EAEAEA' },
  tabsScroll: { paddingHorizontal: 15 },
  tabBtn: { paddingVertical: 8, paddingHorizontal: 16, borderRadius: 20, backgroundColor: '#F4F7F5', marginRight: 10 },
  tabBtnActive: { backgroundColor: '#FFF', borderWidth: 1, borderColor: '#58D66D' },
  tabText: { color: '#888', fontWeight: '600', fontSize: 13 },
  tabTextActive: { color: '#58D66D' },
  unreadTabBadge: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#FF3B30', position: 'absolute', top: 0, right: -8 },
  listHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 12 },
  listHeaderText: { fontSize: 12, color: '#888' },
  listHeaderActions: { flexDirection: 'row' },
  headerActionBtn: { flexDirection: 'row', alignItems: 'center' },
  headerActionText: { fontSize: 12, fontWeight: '600', marginLeft: 4 },
  listContainer: { paddingHorizontal: 16, paddingBottom: 40 },
  notificationCard: { backgroundColor: '#FFF', borderRadius: 16, padding: 16, marginBottom: 12, position: 'relative', elevation: 1, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2 },
  unreadCard: { borderLeftWidth: 4, borderLeftColor: '#58D66D' },
  unreadDot: { position: 'absolute', top: 16, left: 16, width: 8, height: 8, borderRadius: 4, backgroundColor: '#FF3B30' },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  notificationTitle: { fontSize: 15, fontWeight: '600', color: '#333' },
  unreadTitle: { fontWeight: '700' },
  notificationMessage: { fontSize: 14, color: '#555', lineHeight: 20 },
  notificationUrdu: { fontSize: 12, color: '#888', marginTop: 4, marginBottom: 12 },
  cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: 1, borderTopColor: '#F0F0F0', paddingTop: 12 },
  typeBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10, borderWidth: 1 },
  typeBadgeText: { fontSize: 10, fontWeight: 'bold' },
  footerRight: { flexDirection: 'row', alignItems: 'center' },
  timeText: { fontSize: 12, color: '#999', marginRight: 12 },
  actionBtnText: { fontSize: 13, fontWeight: '700' },
  emptyContainer: { alignItems: 'center', marginTop: 60 },
  emptyText: { marginTop: 16, fontSize: 16, color: '#888' }
});

export default styles;
