import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F4F7F5' },
  scrollContent: { paddingBottom: 100 },
  headerSection: { backgroundColor: '#58D66D', paddingBottom: 50, borderBottomLeftRadius: 30, borderBottomRightRadius: 30 },
  headerTop: { paddingHorizontal: 20, paddingTop: 10, height: 40 },
  screenTitle: { color: '#FFF', fontSize: 18, fontWeight: 'bold', textAlign: 'center' },
  profileInfoContainer: { alignItems: 'center', marginTop: 10 },
  avatarContainer: { position: 'relative', marginBottom: 16 },
  avatar: { width: 80, height: 80, borderRadius: 40, backgroundColor: '#FFF', justifyContent: 'center', alignItems: 'center', elevation: 5, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 5 },
  avatarText: { fontSize: 32, fontWeight: 'bold', color: '#58D66D' },
  editAvatarBtn: { position: 'absolute', bottom: 0, right: 0, backgroundColor: '#3B82F6', width: 24, height: 24, borderRadius: 12, justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: '#FFF' },
  profileName: { fontSize: 24, fontWeight: 'bold', color: '#FFF' },
  profileNameUrdu: { fontSize: 14, color: 'rgba(255,255,255,0.9)', marginTop: 4 },
  specializationText: { fontSize: 14, color: '#E8F8EA', marginTop: 8 },
  specializationUrduText: { fontSize: 12, color: 'rgba(255,255,255,0.8)', marginTop: 2 },
  verifiedBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF', paddingHorizontal: 16, paddingVertical: 6, borderRadius: 20, marginTop: 16, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 2 },
  verifiedText: { fontSize: 12, fontWeight: 'bold', color: '#58D66D' },
  statsContainer: { flexDirection: 'row', backgroundColor: '#FFF', marginHorizontal: 20, marginTop: 25, borderRadius: 16, paddingVertical: 15, elevation: 3, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, marginBottom: -70 },
  statBox: { flex: 1, alignItems: 'center' },
  statDivider: { width: 1, backgroundColor: '#EAEAEA' },
  statValue: { fontSize: 20, fontWeight: 'bold', color: '#333' },
  statLabel: { fontSize: 10, color: '#888', marginTop: 4, textAlign: 'center' },
  contentSection: { marginTop: 80, paddingHorizontal: 20 },
  sectionHeading: { fontSize: 13, fontWeight: 'bold', color: '#888', marginBottom: 10, marginLeft: 8, letterSpacing: 0.5 },
  menuCard: { backgroundColor: '#FFF', borderRadius: 16, paddingHorizontal: 16, marginBottom: 24, elevation: 1, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2 },
  menuItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 16 },
  menuLeft: { flexDirection: 'row', alignItems: 'center' },
  menuIconBox: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#F4F7F5', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  menuTitle: { fontSize: 15, fontWeight: '600', color: '#333' },
  menuRight: { flexDirection: 'row', alignItems: 'center' },
  menuSubtitle: { fontSize: 13, color: '#999', marginRight: 8 },
  menuSubtitleActive: { fontSize: 13, fontWeight: '600', color: '#58D66D', backgroundColor: '#E8F8EA', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  menuDivider: { height: 1, backgroundColor: '#F0F0F0', marginLeft: 48 },
  logoutBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF', borderRadius: 16, paddingVertical: 16, marginBottom: 40, borderWidth: 1, borderColor: '#FFEBEB' },
  logoutText: { fontSize: 16, fontWeight: 'bold', color: '#FF3B30' },
  bottomNav: { position: 'absolute', bottom: 0, left: 0, right: 0, flexDirection: 'row', backgroundColor: '#FFF', paddingVertical: 12, paddingHorizontal: 20, justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#EEE', elevation: 10 },
  navItem: { alignItems: 'center' },
  navText: { fontSize: 10, color: '#999', marginTop: 4, fontWeight: '500' },
  navProfile: { width: 24, height: 24, borderRadius: 12, backgroundColor: '#E0E0E0', justifyContent: 'center', alignItems: 'center' },
  navProfileActive: { backgroundColor: '#58D66D' },
  navProfileText: { fontSize: 10, fontWeight: 'bold', color: '#888' },
  navProfileTextActive: { color: '#FFF' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: '#FFF', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, minHeight: 300 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  modalTitle: { fontSize: 20, fontWeight: 'bold', color: '#333' },
  modalCloseBtn: { padding: 4 },
  inputGroup: { marginBottom: 20 },
  inputLabel: { fontSize: 14, color: '#666', marginBottom: 8, fontWeight: '500' },
  input: { backgroundColor: '#F4F7F5', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 12, fontSize: 16, color: '#333', borderWidth: 1, borderColor: '#EAEAEA' },
  saveBtn: { backgroundColor: '#58D66D', borderRadius: 12, paddingVertical: 16, alignItems: 'center', marginTop: 10 },
  saveBtnText: { color: '#FFF', fontSize: 16, fontWeight: 'bold' },
  langOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E6E4',
    marginBottom: 12,
    backgroundColor: '#F7F9F8'
  },
  langOptionSelected: {
    borderColor: '#58D66D',
    backgroundColor: '#E8F8EA'
  },
  langOptionText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333'
  },
  langOptionTextSelected: {
    color: '#58D66D',
    fontWeight: 'bold'
  }
});

export default styles;
