import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME, PALETTE } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: { 
      flex: 1, 
      backgroundColor: isDark ? colors.headerBackground : colors.primary, 
    },
    header: { 
      backgroundColor: isDark ? colors.headerBackground : colors.primary, 
      paddingHorizontal: 20, 
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 18 : 22, 
      paddingBottom: 22,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.35 : 0.08,
      shadowRadius: 10,
      elevation: 5,
    },
    headerTopRow: { 
      flexDirection: 'row', 
      alignItems: 'center', 
      justifyContent: 'space-between', 
      marginBottom: 18 
    },
    backBtn: { 
      minWidth: 44,
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
    },
    titleContainer: { alignItems: 'center' },
    headerTitle: { fontSize: 22, fontWeight: '800', color: '#FFF', letterSpacing: -0.3 },
    headerSubtitle: { fontSize: 13, color: 'rgba(255,255,255,0.85)', marginTop: 2, fontWeight: '500' },
    newBtn: { backgroundColor: 'rgba(255,255,255,0.22)', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 16 },
    newBtnText: { color: '#FFF', fontWeight: '800', fontSize: 13 },
    tabsContainer: { 
      flexDirection: 'row', 
      backgroundColor: isDark ? 'rgba(0,0,0,0.3)' : 'rgba(255,255,255,0.22)', 
      borderRadius: 22, 
      padding: 4 
    },
    tabBtn: { flex: 1, paddingVertical: 10, borderRadius: 18, alignItems: 'center', minHeight: 40, justifyContent: 'center' },
    tabBtnActive: { backgroundColor: isDark ? colors.card : '#FFF' },
    tabBtnInactive: { backgroundColor: 'transparent' },
    tabText: { fontWeight: '700', fontSize: 13 },
    tabTextActive: { color: colors.primary },
    tabTextInactive: { color: isDark ? colors.textSecondary : '#FFF' },

    historyContainer: { flex: 1, backgroundColor: colors.background },
    searchContainer: { 
      margin: 16, 
      backgroundColor: colors.inputBackground, 
      borderRadius: 22, 
      paddingHorizontal: 16, 
      height: 48, 
      justifyContent: 'center', 
      elevation: 2, 
      shadowColor: '#000', 
      shadowOffset: { width: 0, height: 1 }, 
      shadowOpacity: isDark ? 0.2 : 0.05, 
      shadowRadius: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    searchInput: { fontSize: 14, color: colors.inputText },
    statsRow: { flexDirection: 'row', paddingHorizontal: 12, marginBottom: 16, justifyContent: 'space-between' },
    statBox: { 
      flex: 1, 
      backgroundColor: colors.card, 
      borderRadius: 16, 
      padding: 16, 
      marginHorizontal: 4, 
      alignItems: 'center', 
      elevation: 2, 
      shadowColor: '#000', 
      shadowOffset: { width: 0, height: 1 }, 
      shadowOpacity: isDark ? 0.2 : 0.05, 
      shadowRadius: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    statValue: { fontSize: 24, fontWeight: '800', color: colors.textPrimary },
    statLabel: { fontSize: 12, color: colors.textSecondary, marginTop: 4, fontWeight: '600' },
    listContent: { padding: 16, paddingBottom: 100 },
    emptyContainer: { alignItems: 'center', marginTop: 60 },
    emptyText: { marginTop: 16, fontSize: 16, color: colors.textSecondary, fontWeight: '600' },
    historyCard: { 
      backgroundColor: colors.card, 
      borderRadius: 18, 
      padding: 16, 
      marginBottom: 14, 
      elevation: 2, 
      shadowColor: '#000', 
      shadowOffset: { width: 0, height: 1 }, 
      shadowOpacity: isDark ? 0.25 : 0.05, 
      shadowRadius: 6,
      borderWidth: 1,
      borderColor: colors.border,
    },
    historyCardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
    historyFarmerName: { fontSize: 16, fontWeight: '800', color: colors.textPrimary },
    historyDate: { fontSize: 12, color: colors.textSecondary },
    historyDiagnosis: { fontSize: 14, color: colors.primary, fontWeight: '800', marginBottom: 8 },
    historyDivider: { height: 1, backgroundColor: colors.border, marginBottom: 12 },
    historyMedicineText: { fontSize: 14, color: colors.textSecondary, marginBottom: 4 },

    writeNewContainer: { padding: 16, paddingBottom: 100 },
    formSection: { 
      backgroundColor: colors.card, 
      borderRadius: 18, 
      padding: 18, 
      marginBottom: 16, 
      elevation: 2, 
      shadowColor: '#000', 
      shadowOffset: { width: 0, height: 1 }, 
      shadowOpacity: isDark ? 0.25 : 0.05, 
      shadowRadius: 6,
      borderWidth: 1,
      borderColor: colors.border,
    },
    sectionTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 },
    sectionTitleText: { fontSize: 13, color: colors.textSecondary, fontWeight: '800', marginLeft: 8, letterSpacing: 0.5 },
    inputLabel: { fontSize: 12, color: colors.textSecondary, marginBottom: 6, fontWeight: '700' },
    inputField: { 
      borderWidth: 1, 
      borderColor: colors.inputBorder, 
      borderRadius: 22, 
      paddingHorizontal: 16, 
      paddingVertical: 12, 
      fontSize: 14, 
      color: colors.inputText, 
      marginBottom: 16, 
      backgroundColor: colors.inputBackground 
    },
    addMedicineBtn: { color: colors.primary, fontWeight: '800', fontSize: 14 },
    medicineCard: { 
      backgroundColor: colors.surfaceAlt, 
      borderRadius: 14, 
      padding: 14, 
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    medicineIndex: { fontSize: 12, color: colors.primary, fontWeight: '800', marginBottom: 8 },
    medicineDetailsRow: { flexDirection: 'row', justifyContent: 'space-between' },
    halfInput: { flex: 1, marginHorizontal: 4, paddingHorizontal: 12 },
    textArea: { borderRadius: 16, height: 100, textAlignVertical: 'top' },
    sendBtn: { 
      backgroundColor: colors.primary, 
      borderRadius: 22, 
      minHeight: 52,
      justifyContent: 'center',
      alignItems: 'center', 
      elevation: 3, 
      shadowColor: colors.primary, 
      shadowOffset: { width: 0, height: 2 }, 
      shadowOpacity: 0.3, 
      shadowRadius: 4 
    },
    sendBtnText: { color: '#FFF', fontSize: 16, fontWeight: '800' }
  });
};

export default getStyles();
