import { StyleSheet, Platform, StatusBar } from 'react-native';
import { LIGHT_THEME, PALETTE } from '../utils/theme';

export const getStyles = (colors = LIGHT_THEME, isDark = false) => {
  return StyleSheet.create({
    safeArea: { 
      flex: 1, 
      backgroundColor: colors.background 
    },
    scrollContent: { paddingBottom: 110 },
    headerSection: { 
      backgroundColor: isDark ? colors.headerBackground : colors.primary, 
      paddingBottom: 54, 
      borderBottomLeftRadius: 32, 
      borderBottomRightRadius: 32,
      borderBottomWidth: isDark ? 1 : 0,
      borderBottomColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.35 : 0.08,
      shadowRadius: 10,
      elevation: 5,
    },
    headerTop: { 
      paddingHorizontal: 20, 
      paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 10 : 12, 
      height: 48,
      justifyContent: 'center',
    },
    screenTitle: { color: '#FFF', fontSize: 18, fontWeight: '800', textAlign: 'center', letterSpacing: -0.2 },
    profileInfoContainer: { alignItems: 'center', marginTop: 10 },
    avatarContainer: { position: 'relative', marginBottom: 16 },
    avatar: { 
      width: 84, 
      height: 84, 
      borderRadius: 42, 
      backgroundColor: isDark ? colors.card : '#FFF', 
      justifyContent: 'center', 
      alignItems: 'center', 
      elevation: 5, 
      shadowColor: '#000', 
      shadowOffset: { width: 0, height: 2 }, 
      shadowOpacity: isDark ? 0.4 : 0.2, 
      shadowRadius: 6,
      borderWidth: isDark ? 2 : 0,
      borderColor: colors.primary,
    },
    avatarText: { fontSize: 32, fontWeight: '800', color: colors.primary },
    editAvatarBtn: { 
      position: 'absolute', 
      bottom: 0, 
      right: 0, 
      backgroundColor: PALETTE.cobalt500, 
      width: 26, 
      height: 26, 
      borderRadius: 13, 
      justifyContent: 'center', 
      alignItems: 'center', 
      borderWidth: 2, 
      borderColor: '#FFF' 
    },
    profileName: { fontSize: 24, fontWeight: '800', color: '#FFF', letterSpacing: -0.3 },
    profileNameUrdu: { fontSize: 14, color: 'rgba(255,255,255,0.92)', marginTop: 4 },
    specializationText: { fontSize: 14, color: 'rgba(255,255,255,0.9)', marginTop: 8, fontWeight: '600' },
    specializationUrduText: { fontSize: 12, color: 'rgba(255,255,255,0.85)', marginTop: 2 },
    verifiedBadge: { 
      flexDirection: 'row', 
      alignItems: 'center', 
      backgroundColor: isDark ? colors.card : '#FFF', 
      paddingHorizontal: 16, 
      paddingVertical: 7, 
      borderRadius: 20, 
      marginTop: 16, 
      elevation: 2, 
      shadowColor: '#000', 
      shadowOffset: { width: 0, height: 1 }, 
      shadowOpacity: 0.1, 
      shadowRadius: 3,
      borderWidth: isDark ? 1 : 0,
      borderColor: colors.border,
    },
    verifiedText: { fontSize: 12, fontWeight: '800', color: colors.primary },
    statsContainer: { 
      flexDirection: 'row', 
      backgroundColor: colors.card, 
      marginHorizontal: 16, 
      marginTop: 25, 
      borderRadius: 20, 
      paddingVertical: 16, 
      elevation: 4, 
      shadowColor: '#000', 
      shadowOffset: { width: 0, height: 2 }, 
      shadowOpacity: isDark ? 0.3 : 0.1, 
      shadowRadius: 6, 
      marginBottom: -70,
      borderWidth: 1,
      borderColor: colors.border,
    },
    statBox: { flex: 1, alignItems: 'center' },
    statDivider: { width: 1, backgroundColor: colors.border },
    statValue: { fontSize: 20, fontWeight: '800', color: colors.textPrimary },
    statLabel: { fontSize: 10, color: colors.textSecondary, marginTop: 4, textAlign: 'center', fontWeight: '600' },
    contentSection: { marginTop: 86, paddingHorizontal: 16 },
    sectionHeading: { fontSize: 13, fontWeight: '800', color: colors.textSecondary, marginBottom: 10, marginLeft: 8, letterSpacing: 0.5 },
    menuCard: { 
      backgroundColor: colors.card, 
      borderRadius: 20, 
      paddingHorizontal: 16, 
      marginBottom: 20, 
      elevation: 2, 
      shadowColor: '#000', 
      shadowOffset: { width: 0, height: 1 }, 
      shadowOpacity: isDark ? 0.25 : 0.05, 
      shadowRadius: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    menuItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 16, minHeight: 52 },
    menuLeft: { flexDirection: 'row', alignItems: 'center' },
    menuIconBox: { width: 38, height: 38, borderRadius: 19, backgroundColor: isDark ? colors.surfaceAlt : '#F4F7F5', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
    menuTitle: { fontSize: 15, fontWeight: '700', color: colors.textPrimary },
    menuRight: { flexDirection: 'row', alignItems: 'center' },
    menuSubtitle: { fontSize: 13, color: colors.textSecondary, marginRight: 8 },
    menuSubtitleActive: { fontSize: 13, fontWeight: '700', color: colors.primary, backgroundColor: isDark ? 'rgba(16, 185, 129, 0.15)' : '#E8F8EA', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
    menuDivider: { height: 1, backgroundColor: colors.border, marginLeft: 50 },
    logoutBtn: { 
      flexDirection: 'row', 
      alignItems: 'center', 
      justifyContent: 'center', 
      backgroundColor: colors.card, 
      borderRadius: 18, 
      paddingVertical: 16, 
      marginBottom: 40, 
      borderWidth: 1, 
      borderColor: isDark ? 'rgba(239, 68, 68, 0.3)' : '#FFEBEB',
      minHeight: 52,
    },
    logoutText: { fontSize: 16, fontWeight: '800', color: PALETTE.coral500 },
    bottomNav: { 
      position: 'absolute', 
      bottom: 0, 
      left: 0, 
      right: 0, 
      flexDirection: 'row', 
      backgroundColor: colors.card, 
      paddingVertical: 14, 
      paddingHorizontal: 20, 
      justifyContent: 'space-between', 
      borderTopWidth: 1, 
      borderTopColor: colors.border, 
      elevation: 10 
    },
    navItem: { alignItems: 'center' },
    navText: { fontSize: 10, color: colors.textSecondary, marginTop: 4, fontWeight: '600' },
    navProfile: { width: 24, height: 24, borderRadius: 12, backgroundColor: isDark ? colors.surfaceAlt : '#E0E0E0', justifyContent: 'center', alignItems: 'center' },
    navProfileActive: { backgroundColor: colors.primary },
    navProfileText: { fontSize: 10, fontWeight: 'bold', color: colors.textSecondary },
    navProfileTextActive: { color: '#FFF' },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
    modalContent: { 
      backgroundColor: colors.card, 
      borderTopLeftRadius: 28, 
      borderTopRightRadius: 28, 
      padding: 24, 
      minHeight: 300,
      borderTopWidth: 1,
      borderColor: colors.border,
    },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
    modalTitle: { fontSize: 20, fontWeight: '800', color: colors.textPrimary },
    modalCloseBtn: { padding: 4, minWidth: 36, minHeight: 36, justifyContent: 'center', alignItems: 'center' },
    inputGroup: { marginBottom: 20 },
    inputLabel: { fontSize: 14, color: colors.textSecondary, marginBottom: 8, fontWeight: '600' },
    input: { backgroundColor: colors.inputBackground, borderRadius: 14, paddingHorizontal: 16, paddingVertical: 12, fontSize: 15, color: colors.inputText, borderWidth: 1, borderColor: colors.inputBorder },
    saveBtn: { backgroundColor: colors.primary, borderRadius: 16, paddingVertical: 16, minHeight: 52, alignItems: 'center', justifyContent: 'center', marginTop: 10 },
    saveBtnText: { color: '#FFF', fontSize: 16, fontWeight: '800' },
    langOption: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 16,
      paddingHorizontal: 16,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 12,
      backgroundColor: colors.surfaceAlt,
      minHeight: 52,
    },
    langOptionSelected: {
      borderColor: colors.primary,
      backgroundColor: isDark ? 'rgba(16, 185, 129, 0.15)' : '#E8F8EA'
    },
    langOptionText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textPrimary
    },
    langOptionTextSelected: {
      color: colors.primary,
      fontWeight: '800'
    }
  });
};

export default getStyles();
